*** Starting uWSGI 2.0.19.1 (64bit) on [Sat Aug 14 18:44:27 2021] ***
compiled with version: 9.3.0 on 14 August 2021 08:43:18
os: Linux-5.11.0-25-generic #27~20.04.1-Ubuntu SMP Tue Jul 13 17:41:23 UTC 2021
nodename: hoon2-X205TA
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /etc/uwsgi/vassals
detected binary path: /usr/local/bin/uwsgi
chdir() to /home/hoon2/django/
your processes number limit is 7423
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /home/hoon2/django/HPP.sock fd 3
Python version: 3.8.10 (default, Jun  2 2021, 10:49:15)  [GCC 9.4.0]
PEP 405 virtualenv detected: /home/hoon2/django/venv
Set PythonHome to /home/hoon2/django/venv
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x55c50b738d40
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 801944 bytes (783 KB) for 10 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x55c50b738d40 pid: 22029 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 22029)
spawned uWSGI worker 1 (pid: 22031, cores: 1)
spawned uWSGI worker 2 (pid: 22032, cores: 1)
spawned uWSGI worker 3 (pid: 22033, cores: 1)
spawned uWSGI worker 4 (pid: 22034, cores: 1)
spawned uWSGI worker 5 (pid: 22035, cores: 1)
spawned uWSGI worker 6 (pid: 22036, cores: 1)
spawned uWSGI worker 7 (pid: 22037, cores: 1)
spawned uWSGI worker 8 (pid: 22038, cores: 1)
spawned uWSGI worker 9 (pid: 22039, cores: 1)
spawned uWSGI worker 10 (pid: 22040, cores: 1)
[pid: 22040|app: 0|req: 1/1] 192.168.10.107 () {44 vars in 1190 bytes} [Sat Aug 14 18:44:41 2021] GET / => generated 31187 bytes in 130 msecs (HTTP/1.1 200) 5 headers in 168 bytes (2 switches on core 0)
announcing my loyalty to the Emperor...
[pid: 22037|app: 0|req: 1/2] 192.168.10.107 () {44 vars in 1190 bytes} [Sat Aug 14 18:45:08 2021] GET / => generated 31187 bytes in 132 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
announcing my loyalty to the Emperor...
Sat Aug 14 18:47:31 2021 - received message 0 from emperor
SIGINT/SIGQUIT received...killing workers...
worker 2 buried after 2 seconds
worker 5 buried after 2 seconds
worker 6 buried after 2 seconds
worker 7 buried after 2 seconds
worker 8 buried after 2 seconds
worker 10 buried after 2 seconds
worker 1 buried after 3 seconds
worker 3 buried after 3 seconds
worker 4 buried after 3 seconds
worker 9 buried after 3 seconds
goodbye to uWSGI.
VACUUM: unix socket /home/hoon2/django/HPP.sock removed.
*** Starting uWSGI 2.0.19.1 (64bit) on [Sat Aug 14 18:47:36 2021] ***
compiled with version: 9.3.0 on 14 August 2021 08:43:18
os: Linux-5.11.0-25-generic #27~20.04.1-Ubuntu SMP Tue Jul 13 17:41:23 UTC 2021
nodename: hoon2-X205TA
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /etc/uwsgi/vassals
detected binary path: /usr/local/bin/uwsgi
chdir() to /home/hoon2/django/
your processes number limit is 7423
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /home/hoon2/django/HPP.sock fd 3
Python version: 3.8.10 (default, Jun  2 2021, 10:49:15)  [GCC 9.4.0]
PEP 405 virtualenv detected: /home/hoon2/django/venv
Set PythonHome to /home/hoon2/django/venv
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x5632a133dd40
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 801944 bytes (783 KB) for 10 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x5632a133dd40 pid: 22073 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 22073)
spawned uWSGI worker 1 (pid: 22076, cores: 1)
spawned uWSGI worker 2 (pid: 22077, cores: 1)
spawned uWSGI worker 3 (pid: 22078, cores: 1)
spawned uWSGI worker 4 (pid: 22079, cores: 1)
spawned uWSGI worker 5 (pid: 22080, cores: 1)
spawned uWSGI worker 6 (pid: 22081, cores: 1)
spawned uWSGI worker 7 (pid: 22082, cores: 1)
spawned uWSGI worker 8 (pid: 22083, cores: 1)
spawned uWSGI worker 9 (pid: 22084, cores: 1)
spawned uWSGI worker 10 (pid: 22085, cores: 1)
[pid: 22085|app: 0|req: 1/1] 192.168.10.107 () {44 vars in 1190 bytes} [Sat Aug 14 18:47:37 2021] GET / => generated 31187 bytes in 129 msecs (HTTP/1.1 200) 5 headers in 168 bytes (2 switches on core 0)
announcing my loyalty to the Emperor...
[pid: 22084|app: 0|req: 1/2] 192.168.10.107 () {44 vars in 1190 bytes} [Sat Aug 14 18:47:39 2021] GET / => generated 31187 bytes in 131 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
announcing my loyalty to the Emperor...
[pid: 22078|app: 0|req: 1/3] 192.168.10.107 () {44 vars in 1190 bytes} [Sat Aug 14 18:47:42 2021] GET / => generated 31187 bytes in 133 msecs (HTTP/1.1 200) 5 headers in 168 bytes (2 switches on core 0)
announcing my loyalty to the Emperor...
SIGINT/SIGQUIT received...killing workers...
Sat Aug 14 18:53:47 2021 - received message 0 from emperor
worker 1 buried after 2 seconds
worker 2 buried after 2 seconds
worker 3 buried after 2 seconds
worker 6 buried after 2 seconds
worker 9 buried after 2 seconds
worker 4 buried after 3 seconds
worker 5 buried after 3 seconds
worker 7 buried after 3 seconds
worker 8 buried after 3 seconds
worker 10 buried after 3 seconds
goodbye to uWSGI.
VACUUM: unix socket /home/hoon2/django/HPP.sock removed.
*** Starting uWSGI 2.0.19.1 (64bit) on [Sat Aug 14 18:53:52 2021] ***
compiled with version: 9.3.0 on 14 August 2021 08:43:18
os: Linux-5.11.0-25-generic #27~20.04.1-Ubuntu SMP Tue Jul 13 17:41:23 UTC 2021
nodename: hoon2-X205TA
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /etc/uwsgi/vassals
detected binary path: /usr/local/bin/uwsgi
chdir() to /home/hoon2/django/
your processes number limit is 7423
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /home/hoon2/django/HPP.sock fd 3
Python version: 3.8.10 (default, Jun  2 2021, 10:49:15)  [GCC 9.4.0]
PEP 405 virtualenv detected: /home/hoon2/django/venv
Set PythonHome to /home/hoon2/django/venv
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x5604a7662d40
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 801944 bytes (783 KB) for 10 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x5604a7662d40 pid: 22117 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 22117)
spawned uWSGI worker 1 (pid: 22120, cores: 1)
spawned uWSGI worker 2 (pid: 22121, cores: 1)
spawned uWSGI worker 3 (pid: 22122, cores: 1)
spawned uWSGI worker 4 (pid: 22123, cores: 1)
spawned uWSGI worker 5 (pid: 22124, cores: 1)
spawned uWSGI worker 6 (pid: 22125, cores: 1)
spawned uWSGI worker 7 (pid: 22126, cores: 1)
spawned uWSGI worker 8 (pid: 22127, cores: 1)
spawned uWSGI worker 9 (pid: 22128, cores: 1)
spawned uWSGI worker 10 (pid: 22129, cores: 1)
Internal Server Error: /
Traceback (most recent call last):
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 167, in _get_response
    callback, callback_args, callback_kwargs = self.resolve_request(request)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 290, in resolve_request
    resolver_match = resolver.resolve(request.path_info)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/urls/resolvers.py", line 556, in resolve
    for pattern in self.url_patterns:
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/urls/resolvers.py", line 598, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/urls/resolvers.py", line 591, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/hoon2/django/./HPP/urls.py", line 23, in <module>
    path('', include('blog.urls')),
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/hoon2/django/./blog/urls.py", line 8, in <module>
    if settings.DEBUG:
NameError: name 'settings' is not defined
[pid: 22126|app: 0|req: 1/1] 192.168.10.107 () {42 vars in 1159 bytes} [Sat Aug 14 18:53:57 2021] GET / => generated 146058 bytes in 579 msecs (HTTP/1.1 500) 6 headers in 187 bytes (1 switches on core 0)
announcing my loyalty to the Emperor...
SIGINT/SIGQUIT received...killing workers...
Sat Aug 14 18:54:50 2021 - received message 0 from emperor
worker 2 buried after 2 seconds
worker 4 buried after 2 seconds
worker 6 buried after 2 seconds
worker 7 buried after 2 seconds
worker 8 buried after 2 seconds
worker 1 buried after 3 seconds
worker 3 buried after 3 seconds
worker 5 buried after 3 seconds
worker 9 buried after 3 seconds
worker 10 buried after 3 seconds
goodbye to uWSGI.
VACUUM: unix socket /home/hoon2/django/HPP.sock removed.
*** Starting uWSGI 2.0.19.1 (64bit) on [Sat Aug 14 18:54:55 2021] ***
compiled with version: 9.3.0 on 14 August 2021 08:43:18
os: Linux-5.11.0-25-generic #27~20.04.1-Ubuntu SMP Tue Jul 13 17:41:23 UTC 2021
nodename: hoon2-X205TA
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /etc/uwsgi/vassals
detected binary path: /usr/local/bin/uwsgi
chdir() to /home/hoon2/django/
your processes number limit is 7423
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /home/hoon2/django/HPP.sock fd 3
Python version: 3.8.10 (default, Jun  2 2021, 10:49:15)  [GCC 9.4.0]
PEP 405 virtualenv detected: /home/hoon2/django/venv
Set PythonHome to /home/hoon2/django/venv
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x5607debead40
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 801944 bytes (783 KB) for 10 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x5607debead40 pid: 22153 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 22153)
spawned uWSGI worker 1 (pid: 22156, cores: 1)
spawned uWSGI worker 2 (pid: 22157, cores: 1)
spawned uWSGI worker 3 (pid: 22158, cores: 1)
spawned uWSGI worker 4 (pid: 22159, cores: 1)
spawned uWSGI worker 5 (pid: 22160, cores: 1)
spawned uWSGI worker 6 (pid: 22161, cores: 1)
spawned uWSGI worker 7 (pid: 22162, cores: 1)
spawned uWSGI worker 8 (pid: 22163, cores: 1)
spawned uWSGI worker 9 (pid: 22164, cores: 1)
spawned uWSGI worker 10 (pid: 22165, cores: 1)
Internal Server Error: /
Traceback (most recent call last):
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 167, in _get_response
    callback, callback_args, callback_kwargs = self.resolve_request(request)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 290, in resolve_request
    resolver_match = resolver.resolve(request.path_info)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/urls/resolvers.py", line 556, in resolve
    for pattern in self.url_patterns:
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/urls/resolvers.py", line 598, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/urls/resolvers.py", line 591, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/hoon2/django/./HPP/urls.py", line 27, in <module>
    if settings.DEBUG:
NameError: name 'settings' is not defined
[pid: 22157|app: 0|req: 1/1] 192.168.10.107 () {44 vars in 1190 bytes} [Sat Aug 14 18:54:56 2021] GET / => generated 110281 bytes in 506 msecs (HTTP/1.1 500) 6 headers in 187 bytes (1 switches on core 0)
announcing my loyalty to the Emperor...
Internal Server Error: /
Traceback (most recent call last):
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 167, in _get_response
    callback, callback_args, callback_kwargs = self.resolve_request(request)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 290, in resolve_request
    resolver_match = resolver.resolve(request.path_info)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/urls/resolvers.py", line 556, in resolve
    for pattern in self.url_patterns:
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/urls/resolvers.py", line 598, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/urls/resolvers.py", line 591, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/hoon2/django/./HPP/urls.py", line 27, in <module>
    if settings.DEBUG:
NameError: name 'settings' is not defined
[pid: 22159|app: 0|req: 1/2] 192.168.10.107 () {44 vars in 1190 bytes} [Sat Aug 14 18:54:57 2021] GET / => generated 110281 bytes in 504 msecs (HTTP/1.1 500) 6 headers in 187 bytes (1 switches on core 0)
announcing my loyalty to the Emperor...
SIGINT/SIGQUIT received...killing workers...
Sat Aug 14 18:55:46 2021 - received message 0 from emperor
worker 1 buried after 2 seconds
worker 4 buried after 2 seconds
worker 5 buried after 2 seconds
worker 6 buried after 2 seconds
worker 2 buried after 3 seconds
worker 3 buried after 3 seconds
worker 7 buried after 3 seconds
worker 8 buried after 3 seconds
worker 9 buried after 3 seconds
worker 10 buried after 3 seconds
goodbye to uWSGI.
VACUUM: unix socket /home/hoon2/django/HPP.sock removed.
*** Starting uWSGI 2.0.19.1 (64bit) on [Sat Aug 14 18:55:51 2021] ***
compiled with version: 9.3.0 on 14 August 2021 08:43:18
os: Linux-5.11.0-25-generic #27~20.04.1-Ubuntu SMP Tue Jul 13 17:41:23 UTC 2021
nodename: hoon2-X205TA
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /etc/uwsgi/vassals
detected binary path: /usr/local/bin/uwsgi
chdir() to /home/hoon2/django/
your processes number limit is 7423
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /home/hoon2/django/HPP.sock fd 3
Python version: 3.8.10 (default, Jun  2 2021, 10:49:15)  [GCC 9.4.0]
PEP 405 virtualenv detected: /home/hoon2/django/venv
Set PythonHome to /home/hoon2/django/venv
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x561bbb4d8d40
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 801944 bytes (783 KB) for 10 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x561bbb4d8d40 pid: 22183 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 22183)
spawned uWSGI worker 1 (pid: 22186, cores: 1)
spawned uWSGI worker 2 (pid: 22187, cores: 1)
spawned uWSGI worker 3 (pid: 22188, cores: 1)
spawned uWSGI worker 4 (pid: 22189, cores: 1)
spawned uWSGI worker 5 (pid: 22190, cores: 1)
spawned uWSGI worker 6 (pid: 22191, cores: 1)
spawned uWSGI worker 7 (pid: 22192, cores: 1)
spawned uWSGI worker 8 (pid: 22193, cores: 1)
spawned uWSGI worker 9 (pid: 22194, cores: 1)
spawned uWSGI worker 10 (pid: 22195, cores: 1)
Internal Server Error: /
Traceback (most recent call last):
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 167, in _get_response
    callback, callback_args, callback_kwargs = self.resolve_request(request)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 290, in resolve_request
    resolver_match = resolver.resolve(request.path_info)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/urls/resolvers.py", line 556, in resolve
    for pattern in self.url_patterns:
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/urls/resolvers.py", line 598, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/urls/resolvers.py", line 591, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/hoon2/django/./HPP/urls.py", line 18, in <module>
    import settings
ModuleNotFoundError: No module named 'settings'
[pid: 22186|app: 0|req: 1/1] 192.168.10.107 () {44 vars in 1190 bytes} [Sat Aug 14 18:55:52 2021] GET / => generated 110468 bytes in 427 msecs (HTTP/1.1 500) 6 headers in 187 bytes (1 switches on core 0)
announcing my loyalty to the Emperor...
Sat Aug 14 19:08:28 2021 - received message 0 from emperor
SIGINT/SIGQUIT received...killing workers...
worker 1 buried after 2 seconds
worker 6 buried after 2 seconds
worker 7 buried after 2 seconds
worker 8 buried after 2 seconds
worker 9 buried after 2 seconds
worker 2 buried after 3 seconds
worker 3 buried after 3 seconds
worker 4 buried after 3 seconds
worker 5 buried after 3 seconds
worker 10 buried after 3 seconds
goodbye to uWSGI.
VACUUM: unix socket /home/hoon2/django/HPP.sock removed.
*** Starting uWSGI 2.0.19.1 (64bit) on [Sat Aug 14 19:08:33 2021] ***
compiled with version: 9.3.0 on 14 August 2021 08:43:18
os: Linux-5.11.0-25-generic #27~20.04.1-Ubuntu SMP Tue Jul 13 17:41:23 UTC 2021
nodename: hoon2-X205TA
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /etc/uwsgi/vassals
detected binary path: /usr/local/bin/uwsgi
chdir() to /home/hoon2/django/
your processes number limit is 7423
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /home/hoon2/django/HPP.sock fd 3
Python version: 3.8.10 (default, Jun  2 2021, 10:49:15)  [GCC 9.4.0]
PEP 405 virtualenv detected: /home/hoon2/django/venv
Set PythonHome to /home/hoon2/django/venv
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x557315e5fd40
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 801944 bytes (783 KB) for 10 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x557315e5fd40 pid: 22245 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 22245)
spawned uWSGI worker 1 (pid: 22248, cores: 1)
spawned uWSGI worker 2 (pid: 22249, cores: 1)
spawned uWSGI worker 3 (pid: 22250, cores: 1)
spawned uWSGI worker 4 (pid: 22251, cores: 1)
spawned uWSGI worker 5 (pid: 22252, cores: 1)
spawned uWSGI worker 6 (pid: 22253, cores: 1)
spawned uWSGI worker 7 (pid: 22254, cores: 1)
spawned uWSGI worker 8 (pid: 22255, cores: 1)
spawned uWSGI worker 9 (pid: 22256, cores: 1)
spawned uWSGI worker 10 (pid: 22257, cores: 1)
[pid: 22248|app: 0|req: 1/1] 192.168.10.107 () {44 vars in 1190 bytes} [Sat Aug 14 19:08:34 2021] GET / => generated 31187 bytes in 130 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
announcing my loyalty to the Emperor...
[pid: 22254|app: 0|req: 1/2] 192.168.10.107 () {44 vars in 1190 bytes} [Sat Aug 14 19:08:40 2021] GET / => generated 31187 bytes in 139 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
announcing my loyalty to the Emperor...
[pid: 22255|app: 0|req: 1/3] 192.168.10.107 () {42 vars in 1171 bytes} [Sat Aug 14 19:08:55 2021] GET /admin/ => generated 25841 bytes in 603 msecs (HTTP/1.1 200) 9 headers in 462 bytes (2 switches on core 0)
announcing my loyalty to the Emperor...
[pid: 22254|app: 0|req: 2/4] 192.168.10.107 () {42 vars in 1124 bytes} [Sat Aug 14 19:08:55 2021] GET /jet/jsi18n/ => generated 8330 bytes in 56 msecs (HTTP/1.1 200) 5 headers in 175 bytes (2 switches on core 0)
Not Found: /favicon.ico
Sat Aug 14 19:08:56 2021 - SIGPIPE: writing to a closed pipe/socket/fd (probably the client disconnected) on request /favicon.ico (ip 192.168.10.107) !!!
Sat Aug 14 19:08:56 2021 - uwsgi_response_writev_headers_and_body_do(): Broken pipe [core/writer.c line 306] during GET /favicon.ico (192.168.10.107)
OSError: write error
[pid: 22254|app: 0|req: 3/5] 192.168.10.107 () {42 vars in 1135 bytes} [Sat Aug 14 19:08:55 2021] GET /favicon.ico => generated 0 bytes in 65 msecs (HTTP/1.1 404) 5 headers in 0 bytes (1 switches on core 0)
[pid: 22256|app: 0|req: 1/6] 192.168.10.107 () {44 vars in 1260 bytes} [Sat Aug 14 19:08:55 2021] GET /jet/dashboard/load_dashboard_module/5/ => generated 226 bytes in 163 msecs (HTTP/1.1 200) 6 headers in 172 bytes (1 switches on core 0)
announcing my loyalty to the Emperor...
SIGINT/SIGQUIT received...killing workers...
Sat Aug 14 19:12:22 2021 - received message 0 from emperor
worker 4 buried after 2 seconds
worker 5 buried after 2 seconds
worker 6 buried after 2 seconds
worker 10 buried after 2 seconds
worker 1 buried after 3 seconds
worker 2 buried after 3 seconds
worker 3 buried after 3 seconds
worker 7 buried after 3 seconds
worker 8 buried after 3 seconds
worker 9 buried after 3 seconds
goodbye to uWSGI.
VACUUM: unix socket /home/hoon2/django/HPP.sock removed.
*** Starting uWSGI 2.0.19.1 (64bit) on [Sat Aug 14 19:12:27 2021] ***
compiled with version: 9.3.0 on 14 August 2021 08:43:18
os: Linux-5.11.0-25-generic #27~20.04.1-Ubuntu SMP Tue Jul 13 17:41:23 UTC 2021
nodename: hoon2-X205TA
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /etc/uwsgi/vassals
detected binary path: /usr/local/bin/uwsgi
chdir() to /home/hoon2/django/
your processes number limit is 7423
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /home/hoon2/django/HPP.sock fd 3
Python version: 3.8.10 (default, Jun  2 2021, 10:49:15)  [GCC 9.4.0]
PEP 405 virtualenv detected: /home/hoon2/django/venv
Set PythonHome to /home/hoon2/django/venv
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x55aa3a7ddd40
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 801944 bytes (783 KB) for 10 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x55aa3a7ddd40 pid: 22280 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 22280)
spawned uWSGI worker 1 (pid: 22282, cores: 1)
spawned uWSGI worker 2 (pid: 22283, cores: 1)
spawned uWSGI worker 3 (pid: 22284, cores: 1)
spawned uWSGI worker 4 (pid: 22285, cores: 1)
spawned uWSGI worker 5 (pid: 22286, cores: 1)
spawned uWSGI worker 6 (pid: 22287, cores: 1)
spawned uWSGI worker 7 (pid: 22288, cores: 1)
spawned uWSGI worker 8 (pid: 22289, cores: 1)
spawned uWSGI worker 9 (pid: 22290, cores: 1)
spawned uWSGI worker 10 (pid: 22291, cores: 1)
[pid: 22282|app: 0|req: 1/1] 192.168.10.107 () {44 vars in 1190 bytes} [Sat Aug 14 19:12:28 2021] GET / => generated 31187 bytes in 130 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
announcing my loyalty to the Emperor...
[pid: 22286|app: 0|req: 1/2] 192.168.10.107 () {44 vars in 1190 bytes} [Sat Aug 14 19:16:57 2021] GET / => generated 31187 bytes in 132 msecs (HTTP/1.1 200) 5 headers in 168 bytes (2 switches on core 0)
announcing my loyalty to the Emperor...
Not Found: /Login.htm
[pid: 22291|app: 0|req: 1/3] 82.102.22.53 () {50 vars in 1018 bytes} [Sat Aug 14 19:26:55 2021] POST /Login.htm => generated 2486 bytes in 113 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
announcing my loyalty to the Emperor...
Invalid HTTP_HOST header: 'example.com'. You may need to add 'example.com' to ALLOWED_HOSTS.
Bad Request: /
[pid: 22291|app: 0|req: 2/4] 107.189.3.45 () {32 vars in 369 bytes} [Sat Aug 14 19:30:11 2021] GET / => generated 57106 bytes in 314 msecs (HTTP/1.1 400) 3 headers in 116 bytes (2 switches on core 0)
[pid: 22287|app: 0|req: 1/5] 192.168.10.107 () {44 vars in 1190 bytes} [Sat Aug 14 22:10:03 2021] GET / => generated 31187 bytes in 162 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
announcing my loyalty to the Emperor...
[pid: 22288|app: 0|req: 1/6] 74.120.14.59 () {28 vars in 309 bytes} [Sat Aug 14 23:33:58 2021] GET / => generated 31187 bytes in 129 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
announcing my loyalty to the Emperor...
[pid: 22284|app: 0|req: 1/7] 74.120.14.59 () {34 vars in 444 bytes} [Sat Aug 14 23:33:59 2021] GET / => generated 31187 bytes in 127 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
announcing my loyalty to the Emperor...
Invalid HTTP_HOST header: 'fuwu.sogou.com'. You may need to add 'fuwu.sogou.com' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: 'fuwu.sogou.com'. You may need to add 'fuwu.sogou.com' to ALLOWED_HOSTS.
Bad Request: /404/index.html
[pid: 22290|app: 0|req: 1/8] 222.186.19.235 () {34 vars in 525 bytes} [Sun Aug 15 00:28:09 2021] GET /404/index.html => generated 57681 bytes in 359 msecs (HTTP/1.1 400) 3 headers in 116 bytes (2 switches on core 0)
announcing my loyalty to the Emperor...
Bad Request: /404/index.html
[pid: 22288|app: 0|req: 2/9] 222.186.19.235 () {34 vars in 537 bytes} [Sun Aug 15 00:28:09 2021] GET /404/index.html => generated 57705 bytes in 447 msecs (HTTP/1.1 400) 3 headers in 116 bytes (2 switches on core 0)
[pid: 22290|app: 0|req: 2/10] 192.168.10.107 () {44 vars in 1190 bytes} [Sun Aug 15 00:31:03 2021] GET / => generated 31187 bytes in 146 msecs (HTTP/1.1 200) 5 headers in 168 bytes (2 switches on core 0)
[pid: 22287|app: 0|req: 2/11] 184.105.247.196 () {28 vars in 307 bytes} [Sun Aug 15 02:41:51 2021] GET / => generated 31187 bytes in 19 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
[pid: 22287|app: 0|req: 3/12] 167.248.133.113 () {28 vars in 312 bytes} [Sun Aug 15 07:37:40 2021] GET / => generated 31187 bytes in 19 msecs (HTTP/1.1 200) 5 headers in 168 bytes (2 switches on core 0)
[pid: 22291|app: 0|req: 3/13] 167.248.133.113 () {34 vars in 447 bytes} [Sun Aug 15 07:37:40 2021] GET / => generated 31187 bytes in 54 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
[pid: 22290|app: 0|req: 3/14] 192.168.10.107 () {42 vars in 1159 bytes} [Sun Aug 15 08:54:57 2021] GET / => generated 31187 bytes in 19 msecs (HTTP/1.1 200) 5 headers in 168 bytes (2 switches on core 0)
Invalid HTTP_HOST header: 'www.rawtuna101.art'. You may need to add 'www.rawtuna101.art' to ALLOWED_HOSTS.
Bad Request: /
[pid: 22287|app: 0|req: 4/15] 192.168.10.101 () {66 vars in 1038 bytes} [Sun Aug 15 12:40:58 2021] GET / => generated 59748 bytes in 323 msecs (HTTP/1.1 400) 3 headers in 116 bytes (1 switches on core 0)
Invalid HTTP_HOST header: 'www.rawtuna101.art'. You may need to add 'www.rawtuna101.art' to ALLOWED_HOSTS.
Bad Request: /public
[pid: 22282|app: 0|req: 2/16] 192.168.10.101 () {64 vars in 995 bytes} [Sun Aug 15 12:41:08 2021] GET /public => generated 59659 bytes in 321 msecs (HTTP/1.1 400) 3 headers in 116 bytes (1 switches on core 0)
SIGINT/SIGQUIT received...killing workers...
Sun Aug 15 12:44:23 2021 - received message 0 from emperor
worker 1 buried after 2 seconds
worker 3 buried after 2 seconds
worker 4 buried after 2 seconds
worker 9 buried after 2 seconds
worker 2 buried after 3 seconds
worker 5 buried after 3 seconds
worker 6 buried after 3 seconds
worker 7 buried after 3 seconds
worker 8 buried after 3 seconds
worker 10 buried after 3 seconds
goodbye to uWSGI.
VACUUM: unix socket /home/hoon2/django/HPP.sock removed.
*** Starting uWSGI 2.0.19.1 (64bit) on [Sun Aug 15 12:44:28 2021] ***
compiled with version: 9.3.0 on 14 August 2021 08:43:18
os: Linux-5.11.0-25-generic #27~20.04.1-Ubuntu SMP Tue Jul 13 17:41:23 UTC 2021
nodename: hoon2-X205TA
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /etc/uwsgi/vassals
detected binary path: /usr/local/bin/uwsgi
chdir() to /home/hoon2/django/
your processes number limit is 7423
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /home/hoon2/django/HPP.sock fd 3
Python version: 3.8.10 (default, Jun  2 2021, 10:49:15)  [GCC 9.4.0]
PEP 405 virtualenv detected: /home/hoon2/django/venv
Set PythonHome to /home/hoon2/django/venv
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x558ba9fa3d40
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 801944 bytes (783 KB) for 10 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x558ba9fa3d40 pid: 24861 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 24861)
spawned uWSGI worker 1 (pid: 24864, cores: 1)
spawned uWSGI worker 2 (pid: 24865, cores: 1)
spawned uWSGI worker 3 (pid: 24866, cores: 1)
spawned uWSGI worker 4 (pid: 24867, cores: 1)
spawned uWSGI worker 5 (pid: 24868, cores: 1)
spawned uWSGI worker 6 (pid: 24869, cores: 1)
spawned uWSGI worker 7 (pid: 24870, cores: 1)
spawned uWSGI worker 8 (pid: 24871, cores: 1)
spawned uWSGI worker 9 (pid: 24872, cores: 1)
spawned uWSGI worker 10 (pid: 24873, cores: 1)
Invalid HTTP_HOST header: 'www.rawtuna101.art'. You may need to add 'www.rawtuna101.art' to ALLOWED_HOSTS.
Bad Request: /
[pid: 24872|app: 0|req: 1/1] 192.168.10.101 () {64 vars in 983 bytes} [Sun Aug 15 12:44:35 2021] GET / => generated 59643 bytes in 302 msecs (HTTP/1.1 400) 3 headers in 116 bytes (1 switches on core 0)
announcing my loyalty to the Emperor...
Sun Aug 15 12:44:54 2021 - received message 0 from emperor
SIGINT/SIGQUIT received...killing workers...
worker 1 buried after 2 seconds
worker 2 buried after 2 seconds
worker 4 buried after 2 seconds
worker 7 buried after 2 seconds
worker 9 buried after 2 seconds
worker 3 buried after 3 seconds
worker 5 buried after 3 seconds
worker 6 buried after 3 seconds
worker 8 buried after 3 seconds
worker 10 buried after 3 seconds
goodbye to uWSGI.
VACUUM: unix socket /home/hoon2/django/HPP.sock removed.
*** Starting uWSGI 2.0.19.1 (64bit) on [Sun Aug 15 12:44:59 2021] ***
compiled with version: 9.3.0 on 14 August 2021 08:43:18
os: Linux-5.11.0-25-generic #27~20.04.1-Ubuntu SMP Tue Jul 13 17:41:23 UTC 2021
nodename: hoon2-X205TA
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /etc/uwsgi/vassals
detected binary path: /usr/local/bin/uwsgi
chdir() to /home/hoon2/django/
your processes number limit is 7423
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /home/hoon2/django/HPP.sock fd 3
Python version: 3.8.10 (default, Jun  2 2021, 10:49:15)  [GCC 9.4.0]
PEP 405 virtualenv detected: /home/hoon2/django/venv
Set PythonHome to /home/hoon2/django/venv
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x55a3a40e7d40
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 801944 bytes (783 KB) for 10 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x55a3a40e7d40 pid: 24890 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 24890)
spawned uWSGI worker 1 (pid: 24892, cores: 1)
spawned uWSGI worker 2 (pid: 24893, cores: 1)
spawned uWSGI worker 3 (pid: 24894, cores: 1)
spawned uWSGI worker 4 (pid: 24895, cores: 1)
spawned uWSGI worker 5 (pid: 24896, cores: 1)
spawned uWSGI worker 6 (pid: 24897, cores: 1)
spawned uWSGI worker 7 (pid: 24898, cores: 1)
spawned uWSGI worker 8 (pid: 24899, cores: 1)
spawned uWSGI worker 9 (pid: 24900, cores: 1)
spawned uWSGI worker 10 (pid: 24901, cores: 1)
[pid: 24892|app: 0|req: 1/1] 192.168.10.101 () {66 vars in 1014 bytes} [Sun Aug 15 12:45:00 2021] GET / => generated 31187 bytes in 129 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
announcing my loyalty to the Emperor...
[pid: 24900|app: 0|req: 1/2] 192.168.10.101 () {34 vars in 393 bytes} [Sun Aug 15 12:58:47 2021] GET / => generated 31187 bytes in 128 msecs (HTTP/1.1 200) 5 headers in 168 bytes (2 switches on core 0)
announcing my loyalty to the Emperor...
Not Found: /public
[pid: 24898|app: 0|req: 1/3] 192.168.10.101 () {66 vars in 1026 bytes} [Sun Aug 15 13:36:52 2021] GET /public => generated 2479 bytes in 149 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
announcing my loyalty to the Emperor...
Not Found: /public
[pid: 24900|app: 0|req: 2/4] 192.168.10.101 () {66 vars in 1026 bytes} [Sun Aug 15 13:36:53 2021] GET /public => generated 2479 bytes in 39 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
Not Found: /public
[pid: 24896|app: 0|req: 1/5] 192.168.10.101 () {66 vars in 1026 bytes} [Sun Aug 15 13:36:55 2021] GET /public => generated 2479 bytes in 115 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
announcing my loyalty to the Emperor...
Not Found: /public
[pid: 24893|app: 0|req: 1/6] 192.168.10.101 () {64 vars in 995 bytes} [Sun Aug 15 13:36:59 2021] GET /public => generated 2479 bytes in 113 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
announcing my loyalty to the Emperor...
[pid: 24899|app: 0|req: 1/7] 192.168.10.101 () {64 vars in 983 bytes} [Sun Aug 15 13:37:03 2021] GET / => generated 31187 bytes in 131 msecs (HTTP/1.1 200) 5 headers in 168 bytes (2 switches on core 0)
announcing my loyalty to the Emperor...
Not Found: /public
[pid: 24895|app: 0|req: 1/8] 192.168.10.101 () {64 vars in 995 bytes} [Sun Aug 15 13:37:18 2021] GET /public => generated 2479 bytes in 117 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
announcing my loyalty to the Emperor...
[pid: 24901|app: 0|req: 1/9] 192.168.10.101 () {64 vars in 983 bytes} [Sun Aug 15 13:40:14 2021] GET / => generated 31187 bytes in 128 msecs (HTTP/1.1 200) 5 headers in 168 bytes (2 switches on core 0)
announcing my loyalty to the Emperor...
[pid: 24900|app: 0|req: 3/10] 192.168.10.101 () {64 vars in 983 bytes} [Sun Aug 15 13:40:18 2021] GET / => generated 31187 bytes in 18 msecs (HTTP/1.1 200) 5 headers in 168 bytes (2 switches on core 0)
[pid: 24900|app: 0|req: 4/11] 192.168.10.101 () {64 vars in 983 bytes} [Sun Aug 15 13:41:22 2021] GET / => generated 31187 bytes in 19 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
[pid: 24901|app: 0|req: 2/12] 192.168.10.101 () {66 vars in 1014 bytes} [Sun Aug 15 13:41:22 2021] GET / => generated 31187 bytes in 19 msecs (HTTP/1.1 200) 5 headers in 168 bytes (2 switches on core 0)
[pid: 24897|app: 0|req: 1/13] 192.168.10.101 () {64 vars in 983 bytes} [Sun Aug 15 13:41:26 2021] GET / => generated 31187 bytes in 131 msecs (HTTP/1.1 200) 5 headers in 168 bytes (2 switches on core 0)
announcing my loyalty to the Emperor...
[pid: 24901|app: 0|req: 3/14] 192.168.10.101 () {64 vars in 983 bytes} [Sun Aug 15 13:41:48 2021] GET / => generated 31187 bytes in 18 msecs (HTTP/1.1 200) 5 headers in 168 bytes (2 switches on core 0)
[pid: 24901|app: 0|req: 4/15] 192.168.10.101 () {64 vars in 983 bytes} [Sun Aug 15 13:41:55 2021] GET / => generated 31187 bytes in 19 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
[pid: 24898|app: 0|req: 2/16] 192.168.10.101 () {66 vars in 1014 bytes} [Sun Aug 15 13:43:04 2021] GET / => generated 31187 bytes in 55 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
Not Found: /public
[pid: 24897|app: 0|req: 2/17] 192.168.10.101 () {68 vars in 1042 bytes} [Sun Aug 15 13:44:32 2021] GET /public => generated 2479 bytes in 40 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
Not Found: /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
[pid: 24895|app: 0|req: 2/18] 192.168.10.101 () {42 vars in 774 bytes} [Sun Aug 15 17:15:21 2021] POST /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php => generated 2609 bytes in 29 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
Not Found: /api/jsonws/invoke
[pid: 24899|app: 0|req: 2/19] 192.168.10.101 () {42 vars in 672 bytes} [Sun Aug 15 17:15:21 2021] POST /api/jsonws/invoke => generated 2510 bytes in 38 msecs (HTTP/1.1 404) 5 headers in 159 bytes (2 switches on core 0)
Not Found: /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
[pid: 24896|app: 0|req: 2/20] 192.168.10.101 () {40 vars in 686 bytes} [Sun Aug 15 17:15:27 2021] GET /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php => generated 2608 bytes in 32 msecs (HTTP/1.1 404) 5 headers in 159 bytes (2 switches on core 0)
Not Found: /index.php
[pid: 24896|app: 0|req: 3/21] 192.168.10.101 () {38 vars in 782 bytes} [Sun Aug 15 17:15:27 2021] GET /index.php?s=/Index/\think\app/invokefunction&function=call_user_func_array&vars[0]=md5&vars[1][]=HelloThinkPHP21 => generated 2604 bytes in 33 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
Not Found: /mifs/.;/services/LogService
[pid: 24894|app: 0|req: 1/22] 192.168.10.101 () {44 vars in 741 bytes} [Sun Aug 15 17:15:32 2021] POST /mifs/.;/services/LogService => generated 2542 bytes in 112 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
announcing my loyalty to the Emperor...
[pid: 24901|app: 0|req: 5/23] 192.168.10.101 () {38 vars in 618 bytes} [Sun Aug 15 17:15:33 2021] GET /?XDEBUG_SESSION_START=phpstorm => generated 31187 bytes in 17 msecs (HTTP/1.1 200) 5 headers in 168 bytes (2 switches on core 0)
Not Found: /wp-content/plugins/wp-file-manager/readme.txt
[pid: 24900|app: 0|req: 5/24] 192.168.10.101 () {38 vars in 649 bytes} [Sun Aug 15 17:15:35 2021] GET /wp-content/plugins/wp-file-manager/readme.txt => generated 2593 bytes in 30 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
Not Found: /console/
[pid: 24900|app: 0|req: 6/25] 192.168.10.101 () {38 vars in 575 bytes} [Sun Aug 15 17:15:35 2021] GET /console/ => generated 2482 bytes in 30 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
[pid: 24898|app: 0|req: 3/26] 192.168.10.101 () {36 vars in 431 bytes} [Sun Aug 15 18:51:36 2021] GET / => generated 31187 bytes in 19 msecs (HTTP/1.1 200) 5 headers in 168 bytes (2 switches on core 0)
[pid: 24896|app: 0|req: 4/27] 192.168.10.101 () {40 vars in 571 bytes} [Sun Aug 15 18:51:43 2021] GET / => generated 31187 bytes in 56 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
Not Found: /owa/auth/logon.aspx
[pid: 24897|app: 0|req: 3/28] 192.168.10.101 () {40 vars in 575 bytes} [Sun Aug 15 19:05:08 2021] GET /owa/auth/logon.aspx?url=https%3a%2f%2f1%2fecp%2f => generated 2540 bytes in 30 msecs (HTTP/1.1 404) 5 headers in 159 bytes (2 switches on core 0)
Invalid HTTP_HOST header: 'example.com'. You may need to add 'example.com' to ALLOWED_HOSTS.
Bad Request: /
[pid: 24894|app: 0|req: 2/29] 45.137.20.14 () {32 vars in 369 bytes} [Sun Aug 15 19:43:46 2021] GET / => generated 57236 bytes in 344 msecs (HTTP/1.1 400) 3 headers in 116 bytes (1 switches on core 0)
[pid: 24901|app: 0|req: 6/30] 216.218.206.67 () {28 vars in 306 bytes} [Sun Aug 15 20:12:23 2021] GET / => generated 31187 bytes in 19 msecs (HTTP/1.1 200) 5 headers in 168 bytes (2 switches on core 0)
Invalid HTTP_HOST header: 'www.baidu.com'. You may need to add 'www.baidu.com' to ALLOWED_HOSTS.
Bad Request: /cache/global/img/gs.gif
[pid: 24901|app: 0|req: 7/31] 185.216.140.186 () {32 vars in 436 bytes} [Mon Aug 16 03:10:58 2021] GET /cache/global/img/gs.gif => generated 57550 bytes in 381 msecs (HTTP/1.1 400) 3 headers in 116 bytes (1 switches on core 0)
[pid: 24901|app: 0|req: 8/32] 162.142.125.41 () {28 vars in 311 bytes} [Mon Aug 16 04:23:49 2021] GET / => generated 31187 bytes in 23 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
[pid: 24894|app: 0|req: 3/33] 162.142.125.41 () {34 vars in 446 bytes} [Mon Aug 16 04:23:49 2021] GET / => generated 31187 bytes in 52 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
[pid: 24900|app: 0|req: 7/34] 192.168.10.101 () {36 vars in 431 bytes} [Mon Aug 16 10:52:02 2021] GET / => generated 31187 bytes in 20 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
[pid: 24899|app: 0|req: 3/35] 192.168.10.101 () {34 vars in 392 bytes} [Mon Aug 16 11:42:33 2021] GET / => generated 31187 bytes in 17 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
[pid: 24897|app: 0|req: 4/36] 192.168.10.101 () {40 vars in 563 bytes} [Mon Aug 16 14:06:36 2021] GET / => generated 31187 bytes in 19 msecs (HTTP/1.1 200) 5 headers in 168 bytes (2 switches on core 0)
[pid: 24895|app: 0|req: 3/37] 159.89.101.162 () {34 vars in 481 bytes} [Mon Aug 16 14:06:46 2021] GET / => generated 31187 bytes in 58 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
Invalid HTTP_HOST header: 'example.com'. You may need to add 'example.com' to ALLOWED_HOSTS.
Bad Request: /
[pid: 24895|app: 0|req: 4/38] 45.148.10.241 () {32 vars in 370 bytes} [Mon Aug 16 14:24:03 2021] GET / => generated 57237 bytes in 311 msecs (HTTP/1.1 400) 3 headers in 116 bytes (1 switches on core 0)
[pid: 24900|app: 0|req: 8/39] 167.172.33.174 () {26 vars in 282 bytes} [Mon Aug 16 14:43:50 2021] GET / => generated 31187 bytes in 20 msecs (HTTP/1.0 200) 5 headers in 168 bytes (2 switches on core 0)
[pid: 24896|app: 0|req: 5/40] 192.168.10.101 () {40 vars in 541 bytes} [Mon Aug 16 14:57:16 2021] GET / => generated 31187 bytes in 17 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
Not Found: /favicon.ico
[pid: 24899|app: 0|req: 4/41] 192.168.10.101 () {40 vars in 566 bytes} [Mon Aug 16 14:57:19 2021] GET /favicon.ico => generated 2491 bytes in 32 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
[pid: 24892|app: 0|req: 2/42] 192.168.10.101 () {40 vars in 541 bytes} [Mon Aug 16 14:57:23 2021] GET / => generated 31187 bytes in 19 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
Not Found: /favicon.ico
[pid: 24897|app: 0|req: 5/43] 192.168.10.101 () {40 vars in 566 bytes} [Mon Aug 16 14:57:24 2021] GET /favicon.ico => generated 2491 bytes in 31 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
Invalid HTTP_HOST header: '192.168.0.1:443'. You may need to add '192.168.0.1' to ALLOWED_HOSTS.
Bad Request: /GponForm/diag_Form
[pid: 24897|app: 0|req: 6/44] 192.168.10.101 () {44 vars in 601 bytes} [Mon Aug 16 15:58:03 2021] POST /GponForm/diag_Form?style/ => generated 58649 bytes in 312 msecs (HTTP/1.1 400) 3 headers in 116 bytes (1 switches on core 0)
[pid: 24900|app: 0|req: 9/45] 192.168.10.101 () {40 vars in 479 bytes} [Mon Aug 16 17:16:48 2021] GET / => generated 31187 bytes in 20 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
Not Found: /owa/auth/logon.aspx
[pid: 24897|app: 0|req: 7/46] 192.168.10.101 () {40 vars in 574 bytes} [Mon Aug 16 19:06:37 2021] GET /owa/auth/logon.aspx?url=https%3a%2f%2f1%2fecp%2f => generated 2540 bytes in 30 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
[pid: 24901|app: 0|req: 9/47] 167.248.133.42 () {28 vars in 311 bytes} [Mon Aug 16 19:09:58 2021] GET / => generated 31187 bytes in 18 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
[pid: 24900|app: 0|req: 10/48] 167.248.133.42 () {34 vars in 446 bytes} [Mon Aug 16 19:09:58 2021] GET / => generated 31187 bytes in 17 msecs (HTTP/1.1 200) 5 headers in 168 bytes (2 switches on core 0)
Not Found: /dns-query
[pid: 24901|app: 0|req: 10/49] 192.168.10.101 () {40 vars in 608 bytes} [Mon Aug 16 22:28:25 2021] GET /dns-query?dns=KhUBAAABAAAAAAAAA3d3dwZnb29nbGUDY29tAAABAAE => generated 2529 bytes in 31 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
Invalid HTTP_HOST header: 'doh.rawtuna101.art'. You may need to add 'doh.rawtuna101.art' to ALLOWED_HOSTS.
Bad Request: /dns-query
[pid: 24901|app: 0|req: 11/50] 192.168.10.101 () {42 vars in 708 bytes} [Mon Aug 16 22:28:27 2021] GET /dns-query?dns=KhUBAAABAAAAAAAAA3d3dwZnb29nbGUDY29tAAABAAE => generated 12351 bytes in 89 msecs (HTTP/1.1 400) 3 headers in 132 bytes (2 switches on core 0)
Invalid HTTP_HOST header: 'rawtuna101.art'. You may need to add 'rawtuna101.art' to ALLOWED_HOSTS.
Bad Request: /dns-query
[pid: 24899|app: 0|req: 5/51] 192.168.10.101 () {42 vars in 704 bytes} [Mon Aug 16 22:28:28 2021] GET /dns-query?dns=KhUBAAABAAAAAAAAA3d3dwZnb29nbGUDY29tAAABAAE => generated 12327 bytes in 178 msecs (HTTP/1.1 400) 3 headers in 132 bytes (1 switches on core 0)
Not Found: /dns-query
[pid: 24893|app: 0|req: 2/52] 192.168.10.101 () {40 vars in 608 bytes} [Mon Aug 16 22:28:28 2021] GET /dns-query?dns=KhUBAAABAAAAAAAAA3d3dwZnb29nbGUDY29tAAABAAE => generated 2529 bytes in 32 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
Invalid HTTP_HOST header: 'dns.rawtuna101.art'. You may need to add 'dns.rawtuna101.art' to ALLOWED_HOSTS.
Bad Request: /dns-query
[pid: 24900|app: 0|req: 11/53] 192.168.10.101 () {42 vars in 708 bytes} [Mon Aug 16 22:28:31 2021] GET /dns-query?dns=KhUBAAABAAAAAAAAA3d3dwZnb29nbGUDY29tAAABAAE => generated 12351 bytes in 224 msecs (HTTP/1.1 400) 3 headers in 132 bytes (1 switches on core 0)
Invalid HTTP_HOST header: 'rawtuna101.art'. You may need to add 'rawtuna101.art' to ALLOWED_HOSTS.
Bad Request: /dns-query
[pid: 24898|app: 0|req: 4/54] 192.168.10.101 () {42 vars in 704 bytes} [Mon Aug 16 22:28:32 2021] GET /dns-query?dns=KhUBAAABAAAAAAAAA3d3dwZnb29nbGUDY29tAAABAAE => generated 12327 bytes in 181 msecs (HTTP/1.1 400) 3 headers in 132 bytes (2 switches on core 0)
Invalid HTTP_HOST header: 'doh.rawtuna101.art'. You may need to add 'doh.rawtuna101.art' to ALLOWED_HOSTS.
Bad Request: /dns-query
[pid: 24892|app: 0|req: 3/55] 192.168.10.101 () {42 vars in 708 bytes} [Mon Aug 16 22:28:35 2021] GET /dns-query?dns=KhUBAAABAAAAAAAAA3d3dwZnb29nbGUDY29tAAABAAE => generated 12351 bytes in 186 msecs (HTTP/1.1 400) 3 headers in 132 bytes (1 switches on core 0)
Invalid HTTP_HOST header: 'dns.rawtuna101.art'. You may need to add 'dns.rawtuna101.art' to ALLOWED_HOSTS.
Bad Request: /dns-query
[pid: 24897|app: 0|req: 8/56] 192.168.10.101 () {42 vars in 708 bytes} [Mon Aug 16 22:28:37 2021] GET /dns-query?dns=KhUBAAABAAAAAAAAA3d3dwZnb29nbGUDY29tAAABAAE => generated 12351 bytes in 69 msecs (HTTP/1.1 400) 3 headers in 132 bytes (1 switches on core 0)
Invalid HTTP_HOST header: 'doh.rawtuna101.art'. You may need to add 'doh.rawtuna101.art' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: 'doh.rawtuna101.art'. You may need to add 'doh.rawtuna101.art' to ALLOWED_HOSTS.
Bad Request: /dns-query
[pid: 24894|app: 0|req: 4/57] 192.168.10.101 () {40 vars in 615 bytes} [Mon Aug 16 22:28:45 2021] GET /dns-query?dns=KhUBAAABAAAAAAAAA3d3dwZnb29nbGUDY29tAAABAAE => generated 12256 bytes in 70 msecs (HTTP/1.1 400) 3 headers in 132 bytes (1 switches on core 0)
Bad Request: /dns-query
[pid: 24896|app: 0|req: 6/58] 192.168.10.101 () {40 vars in 615 bytes} [Mon Aug 16 22:28:45 2021] GET /dns-query?dns=KhUBAAABAAAAAAAAA3d3dwZnb29nbGUDY29tAAABAAE => generated 12256 bytes in 173 msecs (HTTP/1.1 400) 3 headers in 132 bytes (1 switches on core 0)
Invalid HTTP_HOST header: 'dns.rawtuna101.art'. You may need to add 'dns.rawtuna101.art' to ALLOWED_HOSTS.
Bad Request: /dns-query
[pid: 24896|app: 0|req: 7/59] 192.168.10.101 () {40 vars in 615 bytes} [Mon Aug 16 22:28:45 2021] GET /dns-query?dns=KhUBAAABAAAAAAAAA3d3dwZnb29nbGUDY29tAAABAAE => generated 12256 bytes in 113 msecs (HTTP/1.1 400) 3 headers in 132 bytes (1 switches on core 0)
Invalid HTTP_HOST header: 'dns.rawtuna101.art'. You may need to add 'dns.rawtuna101.art' to ALLOWED_HOSTS.
Bad Request: /dns-query
[pid: 24893|app: 0|req: 3/60] 192.168.10.101 () {40 vars in 615 bytes} [Mon Aug 16 22:28:46 2021] GET /dns-query?dns=KhUBAAABAAAAAAAAA3d3dwZnb29nbGUDY29tAAABAAE => generated 12256 bytes in 185 msecs (HTTP/1.1 400) 3 headers in 132 bytes (2 switches on core 0)
[pid: 24900|app: 0|req: 12/61] 64.62.197.182 () {28 vars in 305 bytes} [Tue Aug 17 00:12:28 2021] GET / => generated 31187 bytes in 18 msecs (HTTP/1.1 200) 5 headers in 168 bytes (2 switches on core 0)
Not Found: /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
[pid: 24900|app: 0|req: 13/62] 192.168.10.101 () {42 vars in 774 bytes} [Tue Aug 17 01:35:45 2021] POST /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php => generated 2609 bytes in 30 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
Not Found: /api/jsonws/invoke
[pid: 24896|app: 0|req: 8/63] 192.168.10.101 () {42 vars in 672 bytes} [Tue Aug 17 01:35:48 2021] POST /api/jsonws/invoke => generated 2510 bytes in 31 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
Not Found: /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
[pid: 24895|app: 0|req: 5/64] 192.168.10.101 () {40 vars in 686 bytes} [Tue Aug 17 01:35:48 2021] GET /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php => generated 2608 bytes in 30 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
[pid: 24894|app: 0|req: 5/65] 192.168.10.101 () {38 vars in 618 bytes} [Tue Aug 17 01:35:51 2021] GET /?XDEBUG_SESSION_START=phpstorm => generated 31187 bytes in 18 msecs (HTTP/1.1 200) 5 headers in 168 bytes (2 switches on core 0)
Not Found: /index.php
[pid: 24896|app: 0|req: 9/66] 192.168.10.101 () {38 vars in 782 bytes} [Tue Aug 17 01:35:51 2021] GET /index.php?s=/Index/\think\app/invokefunction&function=call_user_func_array&vars[0]=md5&vars[1][]=HelloThinkPHP21 => generated 2604 bytes in 33 msecs (HTTP/1.1 404) 5 headers in 159 bytes (2 switches on core 0)
Not Found: /wp-content/plugins/wp-file-manager/readme.txt
[pid: 24899|app: 0|req: 6/67] 192.168.10.101 () {38 vars in 649 bytes} [Tue Aug 17 01:35:54 2021] GET /wp-content/plugins/wp-file-manager/readme.txt => generated 2593 bytes in 30 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
Not Found: /mifs/.;/services/LogService
[pid: 24897|app: 0|req: 9/68] 192.168.10.101 () {44 vars in 741 bytes} [Tue Aug 17 01:35:56 2021] POST /mifs/.;/services/LogService => generated 2542 bytes in 30 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
Not Found: /Autodiscover/Autodiscover.xml
[pid: 24892|app: 0|req: 4/69] 192.168.10.101 () {42 vars in 698 bytes} [Tue Aug 17 01:35:57 2021] POST /Autodiscover/Autodiscover.xml => generated 2546 bytes in 31 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
Not Found: /console/
[pid: 24893|app: 0|req: 4/70] 192.168.10.101 () {38 vars in 575 bytes} [Tue Aug 17 01:35:59 2021] GET /console/ => generated 2482 bytes in 30 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
Not Found: /_ignition/execute-solution
[pid: 24901|app: 0|req: 12/71] 192.168.10.101 () {40 vars in 664 bytes} [Tue Aug 17 01:36:00 2021] GET /_ignition/execute-solution => generated 2536 bytes in 32 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
[pid: 24895|app: 0|req: 6/72] 192.168.10.101 () {38 vars in 559 bytes} [Tue Aug 17 01:36:03 2021] GET / => generated 31187 bytes in 19 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
Not Found: /owa/auth/x.js
[pid: 24898|app: 0|req: 5/73] 192.168.10.101 () {42 vars in 641 bytes} [Tue Aug 17 01:50:28 2021] GET /owa/auth/x.js => generated 2493 bytes in 29 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
Not Found: /ecp/Current/exporttool/microsoft.exchange.ediscovery.exporttool.application
[pid: 24898|app: 0|req: 6/74] 192.168.10.101 () {40 vars in 629 bytes} [Tue Aug 17 02:03:32 2021] GET /ecp/Current/exporttool/microsoft.exchange.ediscovery.exporttool.application => generated 2679 bytes in 33 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
Not Found: /owa/auth/logon.aspx
[pid: 24898|app: 0|req: 7/75] 192.168.10.101 () {40 vars in 518 bytes} [Tue Aug 17 02:14:57 2021] GET /owa/auth/logon.aspx => generated 2511 bytes in 31 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
[pid: 24900|app: 0|req: 14/76] 74.120.14.43 () {28 vars in 309 bytes} [Tue Aug 17 03:09:27 2021] GET / => generated 31187 bytes in 19 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
[pid: 24899|app: 0|req: 7/77] 74.120.14.43 () {34 vars in 444 bytes} [Tue Aug 17 03:09:27 2021] GET / => generated 31187 bytes in 19 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
Not Found: /actuator/health
[pid: 24901|app: 0|req: 13/78] 192.168.10.101 () {40 vars in 510 bytes} [Tue Aug 17 03:33:06 2021] GET /actuator/health => generated 2499 bytes in 30 msecs (HTTP/1.1 404) 5 headers in 159 bytes (2 switches on core 0)
[pid: 24901|app: 0|req: 14/79] 192.168.10.101 () {52 vars in 698 bytes} [Tue Aug 17 06:13:47 2021] GET / => generated 31187 bytes in 18 msecs (HTTP/1.1 200) 5 headers in 168 bytes (2 switches on core 0)
[pid: 24899|app: 0|req: 8/80] 192.168.10.101 () {36 vars in 459 bytes} [Tue Aug 17 07:25:34 2021] GET / => generated 31187 bytes in 17 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
Not Found: /ecp/Current/exporttool/microsoft.exchange.ediscovery.exporttool.application
[pid: 24899|app: 0|req: 9/81] 192.168.10.101 () {40 vars in 630 bytes} [Tue Aug 17 07:49:39 2021] GET /ecp/Current/exporttool/microsoft.exchange.ediscovery.exporttool.application => generated 2679 bytes in 30 msecs (HTTP/1.1 404) 5 headers in 159 bytes (2 switches on core 0)
[pid: 24900|app: 0|req: 15/82] 192.168.10.101 () {40 vars in 479 bytes} [Tue Aug 17 08:54:37 2021] GET / => generated 31187 bytes in 18 msecs (HTTP/1.1 200) 5 headers in 168 bytes (2 switches on core 0)
[pid: 24900|app: 0|req: 16/83] 74.82.47.3 () {28 vars in 302 bytes} [Tue Aug 17 09:12:59 2021] GET / => generated 31187 bytes in 19 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
[pid: 24901|app: 0|req: 15/84] 162.142.125.58 () {28 vars in 311 bytes} [Tue Aug 17 11:34:22 2021] GET / => generated 31187 bytes in 19 msecs (HTTP/1.1 200) 5 headers in 168 bytes (2 switches on core 0)
[pid: 24893|app: 0|req: 5/85] 162.142.125.58 () {34 vars in 446 bytes} [Tue Aug 17 11:34:22 2021] GET / => generated 31187 bytes in 52 msecs (HTTP/1.1 200) 5 headers in 168 bytes (2 switches on core 0)
[pid: 24898|app: 0|req: 8/86] 192.168.10.101 () {40 vars in 603 bytes} [Tue Aug 17 12:01:48 2021] GET / => generated 31187 bytes in 20 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
[pid: 24899|app: 0|req: 10/87] 192.168.10.101 () {34 vars in 390 bytes} [Tue Aug 17 12:53:21 2021] GET / => generated 31187 bytes in 19 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
[pid: 24899|app: 0|req: 11/88] 192.168.10.101 () {34 vars in 395 bytes} [Tue Aug 17 13:33:23 2021] GET / => generated 31187 bytes in 20 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
[pid: 24901|app: 0|req: 16/89] 192.168.10.101 () {40 vars in 526 bytes} [Tue Aug 17 13:33:24 2021] GET / => generated 31187 bytes in 20 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
Not Found: /favicon.ico
[pid: 24899|app: 0|req: 12/90] 192.168.10.101 () {40 vars in 624 bytes} [Tue Aug 17 13:35:34 2021] GET /favicon.ico => generated 2487 bytes in 30 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
[pid: 24900|app: 0|req: 17/91] 192.168.10.101 () {40 vars in 569 bytes} [Tue Aug 17 14:12:44 2021] GET / => generated 31187 bytes in 19 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
Invalid HTTP_HOST header: '192.168.0.1:443'. You may need to add '192.168.0.1' to ALLOWED_HOSTS.
Bad Request: /GponForm/diag_Form
[pid: 24898|app: 0|req: 9/92] 192.168.10.101 () {44 vars in 601 bytes} [Tue Aug 17 14:25:00 2021] POST /GponForm/diag_Form?style/ => generated 58649 bytes in 200 msecs (HTTP/1.1 400) 3 headers in 116 bytes (1 switches on core 0)
Not Found: /owa/auth/logon.aspx
[pid: 24897|app: 0|req: 10/93] 192.168.10.101 () {40 vars in 575 bytes} [Tue Aug 17 19:07:38 2021] GET /owa/auth/logon.aspx?url=https%3a%2f%2f1%2fecp%2f => generated 2540 bytes in 30 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
Invalid HTTP_HOST header: '192.168.0.1:443'. You may need to add '192.168.0.1' to ALLOWED_HOSTS.
Bad Request: /GponForm/diag_Form
[pid: 24897|app: 0|req: 11/94] 192.168.10.101 () {44 vars in 601 bytes} [Tue Aug 17 22:51:15 2021] POST /GponForm/diag_Form?style/ => generated 58649 bytes in 152 msecs (HTTP/1.1 400) 3 headers in 116 bytes (1 switches on core 0)
[pid: 24900|app: 0|req: 18/95] 66.240.219.146 () {34 vars in 535 bytes} [Wed Aug 18 00:20:02 2021] GET / => generated 31187 bytes in 20 msecs (HTTP/1.1 200) 5 headers in 168 bytes (2 switches on core 0)
Not Found: /index.php
[pid: 24897|app: 0|req: 12/96] 192.168.10.101 () {38 vars in 782 bytes} [Wed Aug 18 01:11:39 2021] GET /index.php?s=/Index/\think\app/invokefunction&function=call_user_func_array&vars[0]=md5&vars[1][]=HelloThinkPHP21 => generated 2604 bytes in 32 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
Not Found: /api/jsonws/invoke
[pid: 24893|app: 0|req: 6/97] 192.168.10.101 () {42 vars in 672 bytes} [Wed Aug 18 01:11:41 2021] POST /api/jsonws/invoke => generated 2510 bytes in 34 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
[pid: 24899|app: 0|req: 13/98] 192.168.10.101 () {38 vars in 618 bytes} [Wed Aug 18 01:11:44 2021] GET /?XDEBUG_SESSION_START=phpstorm => generated 31187 bytes in 19 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
Not Found: /_ignition/execute-solution
[pid: 24896|app: 0|req: 10/99] 192.168.10.101 () {40 vars in 664 bytes} [Wed Aug 18 01:11:49 2021] GET /_ignition/execute-solution => generated 2536 bytes in 30 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
Not Found: /wp-content/plugins/wp-file-manager/readme.txt
[pid: 24900|app: 0|req: 19/100] 192.168.10.101 () {38 vars in 649 bytes} [Wed Aug 18 01:11:49 2021] GET /wp-content/plugins/wp-file-manager/readme.txt => generated 2593 bytes in 31 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
Not Found: /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
[pid: 24900|app: 0|req: 20/101] 192.168.10.101 () {42 vars in 774 bytes} [Wed Aug 18 01:11:53 2021] POST /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php => generated 2609 bytes in 30 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
Not Found: /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
[pid: 24900|app: 0|req: 21/102] 192.168.10.101 () {40 vars in 686 bytes} [Wed Aug 18 01:11:53 2021] GET /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php => generated 2608 bytes in 30 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
Not Found: /Autodiscover/Autodiscover.xml
[pid: 24898|app: 0|req: 10/103] 192.168.10.101 () {42 vars in 698 bytes} [Wed Aug 18 01:11:57 2021] POST /Autodiscover/Autodiscover.xml => generated 2546 bytes in 29 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
Not Found: /owa/auth/x.js
[pid: 24899|app: 0|req: 14/104] 192.168.10.101 () {42 vars in 641 bytes} [Wed Aug 18 01:51:13 2021] GET /owa/auth/x.js => generated 2493 bytes in 31 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
Not Found: /ecp/Current/exporttool/microsoft.exchange.ediscovery.exporttool.application
[pid: 24899|app: 0|req: 15/105] 192.168.10.101 () {40 vars in 629 bytes} [Wed Aug 18 02:04:17 2021] GET /ecp/Current/exporttool/microsoft.exchange.ediscovery.exporttool.application => generated 2679 bytes in 30 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
Not Found: /server-status
[pid: 24901|app: 0|req: 17/106] 192.168.10.101 () {38 vars in 478 bytes} [Wed Aug 18 02:15:09 2021] GET /server-status => generated 2497 bytes in 30 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
Not Found: /owa/auth/logon.aspx
[pid: 24898|app: 0|req: 11/107] 192.168.10.101 () {40 vars in 518 bytes} [Wed Aug 18 02:16:08 2021] GET /owa/auth/logon.aspx => generated 2511 bytes in 26 msecs (HTTP/1.1 404) 5 headers in 159 bytes (2 switches on core 0)
Not Found: /actuator/health
[pid: 24893|app: 0|req: 7/108] 192.168.10.101 () {40 vars in 510 bytes} [Wed Aug 18 03:34:38 2021] GET /actuator/health => generated 2499 bytes in 30 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
[pid: 24899|app: 0|req: 16/109] 192.168.10.101 () {42 vars in 657 bytes} [Wed Aug 18 04:02:39 2021] GET / => generated 31187 bytes in 18 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
[pid: 24896|app: 0|req: 11/110] 192.168.10.101 () {40 vars in 572 bytes} [Wed Aug 18 05:22:21 2021] GET / => generated 31187 bytes in 20 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
Not Found: /ReportServer
[pid: 24897|app: 0|req: 13/111] 192.168.10.101 () {40 vars in 504 bytes} [Wed Aug 18 07:11:05 2021] GET /ReportServer => generated 2490 bytes in 120 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
Not Found: /login
[pid: 24901|app: 0|req: 18/112] 192.168.10.101 () {40 vars in 489 bytes} [Wed Aug 18 07:32:15 2021] GET /login => generated 2469 bytes in 33 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
Not Found: /owa/auth/logon.aspx
[pid: 24901|app: 0|req: 19/113] 192.168.10.101 () {36 vars in 570 bytes} [Wed Aug 18 07:38:34 2021] GET /owa/auth/logon.aspx => generated 2511 bytes in 32 msecs (HTTP/1.1 404) 5 headers in 159 bytes (2 switches on core 0)
Not Found: /ecp/Current/exporttool/microsoft.exchange.ediscovery.exporttool.application
[pid: 24900|app: 0|req: 22/114] 192.168.10.101 () {40 vars in 629 bytes} [Wed Aug 18 07:50:28 2021] GET /ecp/Current/exporttool/microsoft.exchange.ediscovery.exporttool.application => generated 2679 bytes in 34 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
[pid: 24899|app: 0|req: 17/115] 192.168.10.101 () {34 vars in 393 bytes} [Wed Aug 18 09:46:14 2021] GET / => generated 31187 bytes in 50 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
[pid: 24897|app: 0|req: 14/116] 192.168.10.101 () {40 vars in 479 bytes} [Wed Aug 18 10:51:18 2021] GET / => generated 31187 bytes in 18 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
[pid: 24897|app: 0|req: 15/117] 192.168.10.101 () {38 vars in 449 bytes} [Wed Aug 18 10:55:26 2021] GET / => generated 31187 bytes in 17 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
[pid: 24894|app: 0|req: 6/118] 192.168.10.101 () {40 vars in 540 bytes} [Wed Aug 18 11:14:56 2021] GET / => generated 31187 bytes in 19 msecs (HTTP/1.1 200) 5 headers in 168 bytes (2 switches on core 0)
Not Found: /favicon.ico
[pid: 24900|app: 0|req: 23/119] 192.168.10.101 () {40 vars in 568 bytes} [Wed Aug 18 11:15:01 2021] GET /favicon.ico => generated 2491 bytes in 31 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
[pid: 24895|app: 0|req: 7/120] 192.168.10.101 () {42 vars in 596 bytes} [Wed Aug 18 11:52:45 2021] OPTIONS / => generated 31187 bytes in 18 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
Not Found: /owa/auth/logon.aspx
[pid: 24901|app: 0|req: 20/121] 192.168.10.101 () {40 vars in 517 bytes} [Wed Aug 18 12:39:06 2021] GET /owa/auth/logon.aspx => generated 2511 bytes in 30 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
[pid: 24900|app: 0|req: 24/122] 170.130.187.22 () {30 vars in 373 bytes} [Wed Aug 18 13:09:04 2021] GET / => generated 31187 bytes in 20 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
Not Found: /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
[pid: 24894|app: 0|req: 7/123] 192.168.10.101 () {40 vars in 686 bytes} [Wed Aug 18 15:12:35 2021] GET /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php => generated 2608 bytes in 30 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
Not Found: /api/jsonws/invoke
[pid: 24898|app: 0|req: 12/124] 192.168.10.101 () {42 vars in 672 bytes} [Wed Aug 18 15:12:35 2021] POST /api/jsonws/invoke => generated 2510 bytes in 31 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
Not Found: /index.php
[pid: 24901|app: 0|req: 21/125] 192.168.10.101 () {38 vars in 782 bytes} [Wed Aug 18 15:12:37 2021] GET /index.php?s=/Index/\think\app/invokefunction&function=call_user_func_array&vars[0]=md5&vars[1][]=HelloThinkPHP21 => generated 2604 bytes in 31 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
Not Found: /mifs/.;/services/LogService
[pid: 24897|app: 0|req: 16/126] 192.168.10.101 () {44 vars in 741 bytes} [Wed Aug 18 15:12:40 2021] POST /mifs/.;/services/LogService => generated 2542 bytes in 30 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
Not Found: /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
[pid: 24896|app: 0|req: 12/127] 192.168.10.101 () {42 vars in 774 bytes} [Wed Aug 18 15:12:40 2021] POST /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php => generated 2609 bytes in 30 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
Not Found: /wp-content/plugins/wp-file-manager/readme.txt
[pid: 24900|app: 0|req: 25/128] 192.168.10.101 () {38 vars in 649 bytes} [Wed Aug 18 15:12:42 2021] GET /wp-content/plugins/wp-file-manager/readme.txt => generated 2593 bytes in 30 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
[pid: 24892|app: 0|req: 5/129] 192.168.10.101 () {38 vars in 618 bytes} [Wed Aug 18 15:12:43 2021] GET /?XDEBUG_SESSION_START=phpstorm => generated 31187 bytes in 20 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
Not Found: /console/
[pid: 24898|app: 0|req: 13/130] 192.168.10.101 () {38 vars in 575 bytes} [Wed Aug 18 15:12:45 2021] GET /console/ => generated 2482 bytes in 26 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
Not Found: /Autodiscover/Autodiscover.xml
[pid: 24895|app: 0|req: 8/131] 192.168.10.101 () {42 vars in 698 bytes} [Wed Aug 18 15:12:45 2021] POST /Autodiscover/Autodiscover.xml => generated 2546 bytes in 32 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
Not Found: /_ignition/execute-solution
[pid: 24901|app: 0|req: 22/132] 192.168.10.101 () {40 vars in 664 bytes} [Wed Aug 18 15:12:47 2021] GET /_ignition/execute-solution => generated 2536 bytes in 30 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
[pid: 24900|app: 0|req: 26/133] 192.168.10.101 () {38 vars in 559 bytes} [Wed Aug 18 15:12:49 2021] GET / => generated 31187 bytes in 20 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
Invalid HTTP_HOST header: '192.168.0.1:443'. You may need to add '192.168.0.1' to ALLOWED_HOSTS.
Bad Request: /GponForm/diag_Form
[pid: 24901|app: 0|req: 23/134] 192.168.10.101 () {44 vars in 601 bytes} [Wed Aug 18 16:07:30 2021] POST /GponForm/diag_Form?style/ => generated 58649 bytes in 184 msecs (HTTP/1.1 400) 3 headers in 116 bytes (1 switches on core 0)
[pid: 24894|app: 0|req: 8/135] 192.168.10.101 () {50 vars in 914 bytes} [Wed Aug 18 16:30:26 2021] GET / => generated 31187 bytes in 18 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
[pid: 24901|app: 0|req: 24/136] 192.168.10.101 () {36 vars in 425 bytes} [Wed Aug 18 16:48:17 2021] GET / => generated 31187 bytes in 18 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
Not Found: /.DS_Store
[pid: 24901|app: 0|req: 25/137] 192.168.10.101 () {38 vars in 475 bytes} [Wed Aug 18 16:48:19 2021] GET /.DS_Store => generated 2481 bytes in 31 msecs (HTTP/1.1 404) 5 headers in 159 bytes (2 switches on core 0)
Not Found: /nginx.conf
[pid: 24893|app: 0|req: 8/138] 192.168.10.101 () {38 vars in 477 bytes} [Wed Aug 18 16:48:20 2021] GET /nginx.conf => generated 2484 bytes in 32 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
Not Found: /status
[pid: 24896|app: 0|req: 13/139] 192.168.10.101 () {38 vars in 469 bytes} [Wed Aug 18 16:48:21 2021] GET /status => generated 2472 bytes in 31 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
Not Found: /status><script>alert(31337)</script>
Wed Aug 18 16:48:21 2021 - SIGPIPE: writing to a closed pipe/socket/fd (probably the client disconnected) on request /status><script>alert(31337)</script> (ip 192.168.10.101) !!!
Wed Aug 18 16:48:21 2021 - uwsgi_response_writev_headers_and_body_do(): Broken pipe [core/writer.c line 306] during GET /status><script>alert(31337)</script> (192.168.10.101)
OSError: write error
[pid: 24895|app: 0|req: 9/140] 192.168.10.101 () {38 vars in 529 bytes} [Wed Aug 18 16:48:21 2021] GET /status><script>alert(31337)</script> => generated 0 bytes in 66 msecs (HTTP/1.1 404) 5 headers in 0 bytes (0 switches on core 0)
Not Found: /owa/auth/logon.aspx
[pid: 24897|app: 0|req: 17/141] 192.168.10.101 () {40 vars in 575 bytes} [Wed Aug 18 19:07:50 2021] GET /owa/auth/logon.aspx?url=https%3a%2f%2f1%2fecp%2f => generated 2540 bytes in 31 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
[pid: 24901|app: 0|req: 26/142] 192.168.10.101 () {40 vars in 577 bytes} [Wed Aug 18 20:55:29 2021] GET / => generated 31187 bytes in 18 msecs (HTTP/1.1 200) 5 headers in 168 bytes (2 switches on core 0)
[pid: 24901|app: 0|req: 27/143] 192.168.10.101 () {46 vars in 630 bytes} [Wed Aug 18 20:55:39 2021] GET / => generated 31187 bytes in 17 msecs (HTTP/1.1 200) 5 headers in 168 bytes (2 switches on core 0)
[pid: 24901|app: 0|req: 28/144] 192.168.10.101 () {38 vars in 538 bytes} [Wed Aug 18 20:55:58 2021] GET / => generated 31187 bytes in 18 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
[pid: 24898|app: 0|req: 14/145] 192.168.10.101 () {38 vars in 538 bytes} [Wed Aug 18 20:55:59 2021] GET / => generated 31187 bytes in 19 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
[pid: 24899|app: 0|req: 18/146] 192.168.10.101 () {38 vars in 538 bytes} [Wed Aug 18 20:55:59 2021] GET / => generated 31187 bytes in 15 msecs (HTTP/1.1 200) 5 headers in 168 bytes (2 switches on core 0)
[pid: 24898|app: 0|req: 15/147] 192.168.10.101 () {38 vars in 538 bytes} [Wed Aug 18 20:55:59 2021] GET / => generated 31187 bytes in 20 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
[pid: 24895|app: 0|req: 10/148] 192.168.10.101 () {38 vars in 538 bytes} [Wed Aug 18 20:55:59 2021] GET / => generated 31187 bytes in 16 msecs (HTTP/1.1 200) 5 headers in 168 bytes (2 switches on core 0)
Not Found: /robots.txt
[pid: 24901|app: 0|req: 29/149] 192.168.10.101 () {36 vars in 547 bytes} [Wed Aug 18 21:34:03 2021] GET /robots.txt => generated 2484 bytes in 31 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
[pid: 24897|app: 0|req: 18/150] 185.180.143.16 () {34 vars in 486 bytes} [Wed Aug 18 23:34:54 2021] GET / => generated 31187 bytes in 19 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
[pid: 24900|app: 0|req: 27/151] 184.105.247.254 () {28 vars in 307 bytes} [Thu Aug 19 00:42:52 2021] GET / => generated 31187 bytes in 17 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
Not Found: /favicon.ico
[pid: 24899|app: 0|req: 19/152] 183.136.226.2 () {36 vars in 541 bytes} [Thu Aug 19 01:11:56 2021] GET /favicon.ico => generated 2491 bytes in 77 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
Not Found: /owa/auth/x.js
[pid: 24899|app: 0|req: 20/153] 192.168.10.101 () {42 vars in 641 bytes} [Thu Aug 19 01:47:56 2021] GET /owa/auth/x.js => generated 2493 bytes in 30 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
Not Found: /ecp/Current/exporttool/microsoft.exchange.ediscovery.exporttool.application
[pid: 24901|app: 0|req: 30/154] 192.168.10.101 () {40 vars in 629 bytes} [Thu Aug 19 02:01:00 2021] GET /ecp/Current/exporttool/microsoft.exchange.ediscovery.exporttool.application => generated 2679 bytes in 31 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
Not Found: /owa/auth/logon.aspx
[pid: 24901|app: 0|req: 31/155] 192.168.10.101 () {40 vars in 518 bytes} [Thu Aug 19 02:13:27 2021] GET /owa/auth/logon.aspx => generated 2511 bytes in 29 msecs (HTTP/1.1 404) 5 headers in 159 bytes (2 switches on core 0)
Not Found: /actuator/health
[pid: 24901|app: 0|req: 32/156] 192.168.10.101 () {40 vars in 510 bytes} [Thu Aug 19 03:35:48 2021] GET /actuator/health => generated 2499 bytes in 30 msecs (HTTP/1.1 404) 5 headers in 159 bytes (2 switches on core 0)
[pid: 24901|app: 0|req: 33/157] 192.168.10.101 () {36 vars in 511 bytes} [Thu Aug 19 03:59:53 2021] GET / => generated 31187 bytes in 19 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
Invalid HTTP_HOST header: '192.168.0.1:443'. You may need to add '192.168.0.1' to ALLOWED_HOSTS.
Bad Request: /GponForm/diag_Form
[pid: 24898|app: 0|req: 16/158] 192.168.10.101 () {44 vars in 601 bytes} [Thu Aug 19 04:30:03 2021] POST /GponForm/diag_Form?style/ => generated 58649 bytes in 151 msecs (HTTP/1.1 400) 3 headers in 116 bytes (1 switches on core 0)
Not Found: /c/
[pid: 24900|app: 0|req: 28/159] 180.149.125.175 () {34 vars in 494 bytes} [Thu Aug 19 05:56:47 2021] GET /c/ => generated 2464 bytes in 31 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
[pid: 24898|app: 0|req: 17/160] 192.168.10.101 () {40 vars in 571 bytes} [Thu Aug 19 06:38:06 2021] GET / => generated 31187 bytes in 69 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
Not Found: /api/jsonws/invoke
[pid: 24897|app: 0|req: 19/161] 192.168.10.101 () {42 vars in 672 bytes} [Thu Aug 19 07:28:50 2021] POST /api/jsonws/invoke => generated 2510 bytes in 32 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
Not Found: /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
[pid: 24901|app: 0|req: 34/162] 192.168.10.101 () {42 vars in 774 bytes} [Thu Aug 19 07:28:51 2021] POST /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php => generated 2609 bytes in 30 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
Not Found: /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
[pid: 24894|app: 0|req: 9/163] 192.168.10.101 () {40 vars in 686 bytes} [Thu Aug 19 07:28:53 2021] GET /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php => generated 2608 bytes in 32 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
Not Found: /index.php
[pid: 24901|app: 0|req: 35/164] 192.168.10.101 () {38 vars in 782 bytes} [Thu Aug 19 07:28:56 2021] GET /index.php?s=/Index/\think\app/invokefunction&function=call_user_func_array&vars[0]=md5&vars[1][]=HelloThinkPHP21 => generated 2604 bytes in 32 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
Not Found: /mifs/.;/services/LogService
[pid: 24892|app: 0|req: 6/165] 192.168.10.101 () {44 vars in 741 bytes} [Thu Aug 19 07:28:57 2021] POST /mifs/.;/services/LogService => generated 2542 bytes in 62 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
[pid: 24901|app: 0|req: 36/166] 192.168.10.101 () {38 vars in 618 bytes} [Thu Aug 19 07:29:00 2021] GET /?XDEBUG_SESSION_START=phpstorm => generated 31187 bytes in 18 msecs (HTTP/1.1 200) 5 headers in 168 bytes (2 switches on core 0)
Not Found: /wp-content/plugins/wp-file-manager/readme.txt
[pid: 24896|app: 0|req: 14/167] 192.168.10.101 () {38 vars in 649 bytes} [Thu Aug 19 07:29:01 2021] GET /wp-content/plugins/wp-file-manager/readme.txt => generated 2593 bytes in 30 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
Not Found: /console/
[pid: 24898|app: 0|req: 18/168] 192.168.10.101 () {38 vars in 575 bytes} [Thu Aug 19 07:29:03 2021] GET /console/ => generated 2482 bytes in 30 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
Not Found: /Autodiscover/Autodiscover.xml
[pid: 24900|app: 0|req: 29/169] 192.168.10.101 () {42 vars in 698 bytes} [Thu Aug 19 07:29:05 2021] POST /Autodiscover/Autodiscover.xml => generated 2546 bytes in 30 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
Not Found: /ecp/Current/exporttool/microsoft.exchange.ediscovery.exporttool.application
[pid: 24900|app: 0|req: 30/170] 192.168.10.101 () {40 vars in 630 bytes} [Thu Aug 19 07:51:24 2021] GET /ecp/Current/exporttool/microsoft.exchange.ediscovery.exporttool.application => generated 2679 bytes in 31 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
[pid: 24897|app: 0|req: 20/171] 192.168.10.101 () {40 vars in 528 bytes} [Thu Aug 19 08:31:27 2021] GET / => generated 31187 bytes in 19 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
[pid: 24899|app: 0|req: 21/172] 167.248.133.60 () {34 vars in 446 bytes} [Thu Aug 19 08:31:35 2021] GET / => generated 31187 bytes in 18 msecs (HTTP/1.1 200) 5 headers in 168 bytes (2 switches on core 0)
[pid: 24900|app: 0|req: 31/173] 184.105.139.68 () {28 vars in 306 bytes} [Thu Aug 19 09:04:03 2021] GET / => generated 31187 bytes in 23 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
[pid: 24897|app: 0|req: 21/174] 192.168.10.101 () {34 vars in 389 bytes} [Thu Aug 19 09:19:51 2021] GET / => generated 31187 bytes in 19 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
Not Found: /public
[pid: 24892|app: 0|req: 7/175] 192.168.10.101 () {64 vars in 995 bytes} [Thu Aug 19 09:37:51 2021] GET /public => generated 2479 bytes in 28 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
Not Found: /favicon.ico
[pid: 24892|app: 0|req: 8/176] 192.168.10.101 () {62 vars in 937 bytes} [Thu Aug 19 09:37:52 2021] GET /favicon.ico => generated 2494 bytes in 30 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
[pid: 24900|app: 0|req: 32/177] 192.168.10.101 () {64 vars in 983 bytes} [Thu Aug 19 09:38:03 2021] GET / => generated 31187 bytes in 17 msecs (HTTP/1.1 200) 5 headers in 168 bytes (2 switches on core 0)
SIGINT/SIGQUIT received...killing workers...
Thu Aug 19 09:42:32 2021 - received message 0 from emperor
worker 1 buried after 4 seconds
worker 2 buried after 4 seconds
worker 3 buried after 4 seconds
worker 4 buried after 4 seconds
worker 5 buried after 4 seconds
worker 6 buried after 4 seconds
worker 8 buried after 4 seconds
worker 9 buried after 4 seconds
worker 10 buried after 4 seconds
worker 7 buried after 5 seconds
goodbye to uWSGI.
VACUUM: unix socket /home/hoon2/django/HPP.sock removed.
*** Starting uWSGI 2.0.19.1 (64bit) on [Mon Aug 23 10:05:22 2021] ***
compiled with version: 9.3.0 on 14 August 2021 08:43:18
os: Linux-5.11.0-27-generic #29~20.04.1-Ubuntu SMP Wed Aug 11 15:58:17 UTC 2021
nodename: hoon2-X205TA
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /etc/uwsgi/vassals
detected binary path: /usr/local/bin/uwsgi
chdir() to /home/hoon2/django/
your processes number limit is 7423
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /home/hoon2/django/HPP.sock fd 3
Python version: 3.8.10 (default, Jun  2 2021, 10:49:15)  [GCC 9.4.0]
PEP 405 virtualenv detected: /home/hoon2/django/venv
Set PythonHome to /home/hoon2/django/venv
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x55cdb4a9bd40
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 801944 bytes (783 KB) for 10 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 2 seconds on interpreter 0x55cdb4a9bd40 pid: 21713 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 21713)
spawned uWSGI worker 1 (pid: 21715, cores: 1)
spawned uWSGI worker 2 (pid: 21716, cores: 1)
spawned uWSGI worker 3 (pid: 21717, cores: 1)
spawned uWSGI worker 4 (pid: 21718, cores: 1)
spawned uWSGI worker 5 (pid: 21719, cores: 1)
spawned uWSGI worker 6 (pid: 21720, cores: 1)
spawned uWSGI worker 7 (pid: 21721, cores: 1)
spawned uWSGI worker 8 (pid: 21722, cores: 1)
spawned uWSGI worker 9 (pid: 21723, cores: 1)
spawned uWSGI worker 10 (pid: 21724, cores: 1)
[pid: 21718|app: 0|req: 1/1] 14.44.17.80 () {44 vars in 879 bytes} [Mon Aug 23 10:05:26 2021] GET / => generated 31187 bytes in 212 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
announcing my loyalty to the Emperor...
[pid: 21721|app: 0|req: 1/2] 14.44.17.80 () {44 vars in 1001 bytes} [Mon Aug 23 10:51:03 2021] GET / => generated 31149 bytes in 165 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
announcing my loyalty to the Emperor...
[pid: 21716|app: 0|req: 1/3] 14.44.17.80 () {44 vars in 1001 bytes} [Mon Aug 23 10:51:08 2021] GET / => generated 31187 bytes in 132 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
announcing my loyalty to the Emperor...
Not Found: /owa/auth/logon.aspx
[pid: 21723|app: 0|req: 1/4] 192.168.10.101 () {40 vars in 518 bytes} [Mon Aug 23 11:34:56 2021] GET /owa/auth/logon.aspx => generated 2511 bytes in 152 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
announcing my loyalty to the Emperor...
Not Found: /robots.txt
[pid: 21721|app: 0|req: 2/5] 45.95.147.10 () {26 vars in 301 bytes} [Mon Aug 23 12:12:42 2021] HEAD /robots.txt => generated 2489 bytes in 38 msecs (HTTP/1.0 404) 5 headers in 159 bytes (1 switches on core 0)
[pid: 21723|app: 0|req: 2/6] 192.168.10.101 () {40 vars in 480 bytes} [Mon Aug 23 12:25:40 2021] GET / => generated 31187 bytes in 55 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
Not Found: /wp-login.php
[pid: 21724|app: 0|req: 1/7] 192.168.10.101 () {50 vars in 709 bytes} [Mon Aug 23 12:39:27 2021] GET /wp-login.php => generated 2497 bytes in 112 msecs (HTTP/1.1 404) 5 headers in 159 bytes (2 switches on core 0)
announcing my loyalty to the Emperor...
[pid: 21721|app: 0|req: 3/8] 192.168.10.101 () {50 vars in 702 bytes} [Mon Aug 23 12:39:28 2021] GET /?author=1 => generated 31187 bytes in 19 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
[pid: 21715|app: 0|req: 1/9] 192.168.10.101 () {50 vars in 702 bytes} [Mon Aug 23 12:39:29 2021] GET /?author=2 => generated 31187 bytes in 158 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
announcing my loyalty to the Emperor...
[pid: 21721|app: 0|req: 4/10] 192.168.10.101 () {50 vars in 702 bytes} [Mon Aug 23 12:39:29 2021] GET /?author=3 => generated 31187 bytes in 18 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
[pid: 21723|app: 0|req: 3/11] 192.168.10.101 () {50 vars in 702 bytes} [Mon Aug 23 12:39:30 2021] GET /?author=4 => generated 31187 bytes in 18 msecs (HTTP/1.1 200) 5 headers in 168 bytes (2 switches on core 0)
[pid: 21722|app: 0|req: 1/12] 192.168.10.101 () {50 vars in 702 bytes} [Mon Aug 23 12:39:31 2021] GET /?author=5 => generated 31187 bytes in 135 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
announcing my loyalty to the Emperor...
[pid: 21721|app: 0|req: 5/13] 192.168.10.101 () {50 vars in 702 bytes} [Mon Aug 23 12:39:31 2021] GET /?author=6 => generated 31187 bytes in 19 msecs (HTTP/1.1 200) 5 headers in 168 bytes (2 switches on core 0)
[pid: 21718|app: 0|req: 2/14] 192.168.10.101 () {50 vars in 702 bytes} [Mon Aug 23 12:39:32 2021] GET /?author=7 => generated 31187 bytes in 21 msecs (HTTP/1.1 200) 5 headers in 168 bytes (2 switches on core 0)
[pid: 21717|app: 0|req: 1/15] 192.168.10.101 () {50 vars in 702 bytes} [Mon Aug 23 12:39:32 2021] GET /?author=8 => generated 31187 bytes in 130 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
announcing my loyalty to the Emperor...
[pid: 21723|app: 0|req: 4/16] 192.168.10.101 () {50 vars in 702 bytes} [Mon Aug 23 12:39:33 2021] GET /?author=9 => generated 31187 bytes in 18 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
[pid: 21715|app: 0|req: 2/17] 192.168.10.101 () {50 vars in 704 bytes} [Mon Aug 23 12:39:34 2021] GET /?author=10 => generated 31187 bytes in 19 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
[pid: 21719|app: 0|req: 1/18] 192.168.10.101 () {50 vars in 704 bytes} [Mon Aug 23 12:39:34 2021] GET /?author=11 => generated 31187 bytes in 136 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
announcing my loyalty to the Emperor...
[pid: 21723|app: 0|req: 5/19] 192.168.10.101 () {50 vars in 704 bytes} [Mon Aug 23 12:39:35 2021] GET /?author=12 => generated 31187 bytes in 18 msecs (HTTP/1.1 200) 5 headers in 168 bytes (2 switches on core 0)
[pid: 21721|app: 0|req: 6/20] 192.168.10.101 () {50 vars in 704 bytes} [Mon Aug 23 12:39:35 2021] GET /?author=13 => generated 31187 bytes in 18 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
[pid: 21720|app: 0|req: 1/21] 192.168.10.101 () {50 vars in 704 bytes} [Mon Aug 23 12:39:36 2021] GET /?author=14 => generated 31187 bytes in 128 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
announcing my loyalty to the Emperor...
[pid: 21723|app: 0|req: 6/22] 192.168.10.101 () {50 vars in 704 bytes} [Mon Aug 23 12:39:37 2021] GET /?author=15 => generated 31187 bytes in 18 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
[pid: 21722|app: 0|req: 2/23] 192.168.10.101 () {50 vars in 704 bytes} [Mon Aug 23 12:39:37 2021] GET /?author=16 => generated 31187 bytes in 21 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
[pid: 21723|app: 0|req: 7/24] 192.168.10.101 () {50 vars in 704 bytes} [Mon Aug 23 12:39:38 2021] GET /?author=17 => generated 31187 bytes in 17 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
[pid: 21722|app: 0|req: 3/25] 192.168.10.101 () {50 vars in 704 bytes} [Mon Aug 23 12:39:38 2021] GET /?author=18 => generated 31187 bytes in 21 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
[pid: 21723|app: 0|req: 8/26] 192.168.10.101 () {50 vars in 704 bytes} [Mon Aug 23 12:39:39 2021] GET /?author=19 => generated 31187 bytes in 17 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
[pid: 21720|app: 0|req: 2/27] 192.168.10.101 () {50 vars in 704 bytes} [Mon Aug 23 12:39:40 2021] GET /?author=20 => generated 31187 bytes in 19 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
[pid: 21722|app: 0|req: 4/28] 192.168.10.101 () {40 vars in 625 bytes} [Mon Aug 23 13:02:58 2021] GET / => generated 31187 bytes in 19 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
Not Found: /robots.txt
[pid: 21722|app: 0|req: 5/29] 192.168.10.101 () {36 vars in 443 bytes} [Mon Aug 23 13:03:34 2021] GET /robots.txt => generated 2484 bytes in 39 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
Not Found: /sitemap.xml
[pid: 21723|app: 0|req: 9/30] 192.168.10.101 () {36 vars in 445 bytes} [Mon Aug 23 13:03:35 2021] GET /sitemap.xml => generated 2487 bytes in 32 msecs (HTTP/1.1 404) 5 headers in 159 bytes (2 switches on core 0)
Not Found: /.well-known/security.txt
[pid: 21721|app: 0|req: 7/31] 192.168.10.101 () {36 vars in 471 bytes} [Mon Aug 23 13:03:40 2021] GET /.well-known/security.txt => generated 2526 bytes in 31 msecs (HTTP/1.1 404) 5 headers in 159 bytes (2 switches on core 0)
[pid: 21718|app: 0|req: 3/32] 192.168.10.101 () {46 vars in 619 bytes} [Mon Aug 23 13:03:52 2021] GET / => generated 31187 bytes in 18 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
Invalid HTTP_HOST header: '192.168.0.1:443'. You may need to add '192.168.0.1' to ALLOWED_HOSTS.
Bad Request: /GponForm/diag_Form
[pid: 21723|app: 0|req: 10/33] 192.168.10.101 () {44 vars in 601 bytes} [Mon Aug 23 13:18:26 2021] POST /GponForm/diag_Form?style/ => generated 58649 bytes in 400 msecs (HTTP/1.1 400) 3 headers in 116 bytes (1 switches on core 0)
[pid: 21723|app: 0|req: 11/34] 192.168.10.101 () {38 vars in 564 bytes} [Mon Aug 23 14:11:19 2021] GET / => generated 31187 bytes in 19 msecs (HTTP/1.1 200) 5 headers in 168 bytes (2 switches on core 0)
[pid: 21724|app: 0|req: 2/35] 192.168.10.101 () {52 vars in 699 bytes} [Mon Aug 23 14:32:57 2021] GET / => generated 31187 bytes in 55 msecs (HTTP/1.1 200) 5 headers in 168 bytes (2 switches on core 0)
[pid: 21721|app: 0|req: 8/36] 192.168.10.101 () {34 vars in 397 bytes} [Mon Aug 23 15:18:38 2021] GET / => generated 31187 bytes in 19 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
[pid: 21717|app: 0|req: 2/37] 192.168.10.101 () {40 vars in 528 bytes} [Mon Aug 23 15:18:39 2021] GET / => generated 31187 bytes in 20 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
[pid: 21724|app: 0|req: 3/38] 209.141.61.16 () {28 vars in 415 bytes} [Mon Aug 23 15:49:03 2021] GET / => generated 31187 bytes in 11 msecs (HTTP/1.0 200) 5 headers in 168 bytes (2 switches on core 0)
[pid: 21717|app: 0|req: 3/39] 192.168.10.101 () {42 vars in 606 bytes} [Mon Aug 23 17:04:42 2021] GET / => generated 31187 bytes in 18 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
[pid: 21720|app: 0|req: 3/40] 192.168.10.101 () {38 vars in 618 bytes} [Mon Aug 23 19:03:10 2021] GET /?XDEBUG_SESSION_START=phpstorm => generated 31187 bytes in 19 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
Not Found: /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
[pid: 21717|app: 0|req: 4/41] 192.168.10.101 () {40 vars in 686 bytes} [Mon Aug 23 19:03:10 2021] GET /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php => generated 2608 bytes in 111 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
Not Found: /wp-content/plugins/wp-file-manager/readme.txt
[pid: 21716|app: 0|req: 2/42] 192.168.10.101 () {38 vars in 649 bytes} [Mon Aug 23 19:03:14 2021] GET /wp-content/plugins/wp-file-manager/readme.txt => generated 2593 bytes in 41 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
Not Found: /Autodiscover/Autodiscover.xml
[pid: 21722|app: 0|req: 6/43] 192.168.10.101 () {42 vars in 698 bytes} [Mon Aug 23 19:03:14 2021] POST /Autodiscover/Autodiscover.xml => generated 2546 bytes in 30 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
Not Found: /console/
[pid: 21719|app: 0|req: 2/44] 192.168.10.101 () {38 vars in 575 bytes} [Mon Aug 23 19:03:15 2021] GET /console/ => generated 2482 bytes in 38 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
Not Found: /_ignition/execute-solution
[pid: 21715|app: 0|req: 3/45] 192.168.10.101 () {40 vars in 664 bytes} [Mon Aug 23 19:03:18 2021] GET /_ignition/execute-solution => generated 2536 bytes in 39 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
[pid: 21724|app: 0|req: 4/46] 192.168.10.101 () {38 vars in 559 bytes} [Mon Aug 23 19:03:20 2021] GET / => generated 31187 bytes in 19 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
Not Found: /api/jsonws/invoke
[pid: 21724|app: 0|req: 5/47] 192.168.10.101 () {42 vars in 672 bytes} [Mon Aug 23 19:03:23 2021] POST /api/jsonws/invoke => generated 2510 bytes in 52 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
Not Found: /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
[pid: 21724|app: 0|req: 6/48] 192.168.10.101 () {42 vars in 774 bytes} [Mon Aug 23 19:03:26 2021] POST /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php => generated 2609 bytes in 30 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
Not Found: /owa/auth/logon.aspx
[pid: 21724|app: 0|req: 7/49] 192.168.10.101 () {40 vars in 574 bytes} [Mon Aug 23 19:17:04 2021] GET /owa/auth/logon.aspx?url=https%3a%2f%2f1%2fecp%2f => generated 2540 bytes in 30 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
[pid: 21724|app: 0|req: 8/50] 82.156.185.91 () {34 vars in 565 bytes} [Mon Aug 23 20:25:58 2021] GET / => generated 31187 bytes in 20 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
[pid: 21724|app: 0|req: 9/51] 165.227.111.193 () {26 vars in 283 bytes} [Mon Aug 23 22:35:16 2021] GET / => generated 31187 bytes in 20 msecs (HTTP/1.0 200) 5 headers in 168 bytes (2 switches on core 0)
[pid: 21723|app: 0|req: 12/52] 192.168.10.101 () {38 vars in 449 bytes} [Mon Aug 23 23:11:01 2021] GET / => generated 31187 bytes in 18 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
[pid: 21723|app: 0|req: 13/53] 74.82.47.5 () {28 vars in 302 bytes} [Tue Aug 24 01:40:05 2021] GET / => generated 31187 bytes in 19 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
Not Found: /owa/auth/x.js
[pid: 21719|app: 0|req: 3/54] 192.168.10.101 () {42 vars in 640 bytes} [Tue Aug 24 01:57:33 2021] GET /owa/auth/x.js => generated 2493 bytes in 55 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
Not Found: /ecp/Current/exporttool/microsoft.exchange.ediscovery.exporttool.application
[pid: 21721|app: 0|req: 9/55] 192.168.10.101 () {40 vars in 630 bytes} [Tue Aug 24 02:09:20 2021] GET /ecp/Current/exporttool/microsoft.exchange.ediscovery.exporttool.application => generated 2679 bytes in 31 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
Not Found: /owa/auth/logon.aspx
[pid: 21722|app: 0|req: 7/56] 192.168.10.101 () {40 vars in 516 bytes} [Tue Aug 24 02:21:38 2021] GET /owa/auth/logon.aspx => generated 2511 bytes in 31 msecs (HTTP/1.1 404) 5 headers in 159 bytes (2 switches on core 0)
[pid: 21721|app: 0|req: 10/57] 192.168.10.101 () {40 vars in 581 bytes} [Tue Aug 24 03:16:28 2021] GET / => generated 31187 bytes in 20 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
[pid: 21723|app: 0|req: 14/58] 192.168.10.101 () {40 vars in 478 bytes} [Tue Aug 24 03:41:20 2021] GET / => generated 31187 bytes in 18 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
Not Found: /actuator/health
[pid: 21723|app: 0|req: 15/59] 192.168.10.101 () {40 vars in 510 bytes} [Tue Aug 24 04:10:16 2021] GET /actuator/health => generated 2499 bytes in 30 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
[pid: 21722|app: 0|req: 8/60] 192.168.10.101 () {54 vars in 859 bytes} [Tue Aug 24 05:05:00 2021] GET / => generated 31187 bytes in 19 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
[pid: 21719|app: 0|req: 4/61] 192.168.10.101 () {50 vars in 913 bytes} [Tue Aug 24 05:16:27 2021] GET / => generated 31187 bytes in 18 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
[pid: 21723|app: 0|req: 16/62] 192.168.10.101 () {36 vars in 420 bytes} [Tue Aug 24 06:03:53 2021] GET / => generated 31187 bytes in 17 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
Not Found: /aaa9
[pid: 21715|app: 0|req: 4/63] 192.168.10.101 () {38 vars in 562 bytes} [Tue Aug 24 06:03:54 2021] GET /aaa9 => generated 2470 bytes in 31 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
Not Found: /aab9
[pid: 21721|app: 0|req: 11/64] 192.168.10.101 () {38 vars in 562 bytes} [Tue Aug 24 06:03:56 2021] GET /aab9 => generated 2470 bytes in 31 msecs (HTTP/1.1 404) 5 headers in 159 bytes (2 switches on core 0)
Not Found: /aaa9
[pid: 21724|app: 0|req: 10/65] 192.168.10.101 () {38 vars in 562 bytes} [Tue Aug 24 06:04:03 2021] GET /aaa9 => generated 2470 bytes in 31 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
Not Found: /aab9
[pid: 21724|app: 0|req: 11/66] 192.168.10.101 () {38 vars in 562 bytes} [Tue Aug 24 06:04:05 2021] GET /aab9 => generated 2470 bytes in 55 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
[pid: 21723|app: 0|req: 17/67] 192.168.10.101 () {40 vars in 569 bytes} [Tue Aug 24 06:33:12 2021] GET / => generated 31187 bytes in 18 msecs (HTTP/1.1 200) 5 headers in 168 bytes (2 switches on core 0)
[pid: 21723|app: 0|req: 18/68] 192.168.10.101 () {50 vars in 826 bytes} [Tue Aug 24 07:49:12 2021] GET / => generated 31187 bytes in 20 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
Not Found: /ecp/Current/exporttool/microsoft.exchange.ediscovery.exporttool.application
[pid: 21724|app: 0|req: 12/69] 192.168.10.101 () {40 vars in 630 bytes} [Tue Aug 24 07:56:34 2021] GET /ecp/Current/exporttool/microsoft.exchange.ediscovery.exporttool.application => generated 2679 bytes in 30 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
[pid: 21724|app: 0|req: 13/70] 192.168.10.101 () {40 vars in 542 bytes} [Tue Aug 24 08:24:25 2021] GET / => generated 31187 bytes in 20 msecs (HTTP/1.1 200) 5 headers in 168 bytes (2 switches on core 0)
Not Found: /favicon.ico
[pid: 21721|app: 0|req: 12/71] 192.168.10.101 () {40 vars in 567 bytes} [Tue Aug 24 08:24:27 2021] GET /favicon.ico => generated 2491 bytes in 30 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
[pid: 21720|app: 0|req: 4/72] 192.168.10.101 () {68 vars in 1227 bytes} [Tue Aug 24 08:42:21 2021] GET / => generated 31187 bytes in 17 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
Internal Server Error: /
Traceback (most recent call last):
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/hoon2/django/./blog/views.py", line 5, in Mainpageview
    return render(request, 'blog/main.html', {})
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: blog/index.html
[pid: 21720|app: 0|req: 5/73] 192.168.10.101 () {70 vars in 1259 bytes} [Tue Aug 24 09:10:07 2021] GET / => generated 69799 bytes in 732 msecs (HTTP/1.1 500) 6 headers in 186 bytes (1 switches on core 0)
Not Found: /favicon.ico
[pid: 21723|app: 0|req: 19/74] 192.168.10.101 () {70 vars in 1219 bytes} [Tue Aug 24 09:10:09 2021] GET /favicon.ico => generated 2494 bytes in 29 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
SIGINT/SIGQUIT received...killing workers...
Tue Aug 24 09:13:01 2021 - received message 0 from emperor
worker 10 buried after 2 seconds
worker 1 buried after 3 seconds
worker 2 buried after 3 seconds
worker 3 buried after 3 seconds
worker 4 buried after 3 seconds
worker 5 buried after 3 seconds
worker 6 buried after 3 seconds
worker 7 buried after 3 seconds
worker 8 buried after 3 seconds
worker 9 buried after 3 seconds
goodbye to uWSGI.
VACUUM: unix socket /home/hoon2/django/HPP.sock removed.
*** Starting uWSGI 2.0.19.1 (64bit) on [Tue Aug 24 09:13:06 2021] ***
compiled with version: 9.3.0 on 14 August 2021 08:43:18
os: Linux-5.11.0-27-generic #29~20.04.1-Ubuntu SMP Wed Aug 11 15:58:17 UTC 2021
nodename: hoon2-X205TA
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /etc/uwsgi/vassals
detected binary path: /usr/local/bin/uwsgi
chdir() to /home/hoon2/django/
your processes number limit is 7423
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /home/hoon2/django/HPP.sock fd 3
Python version: 3.8.10 (default, Jun  2 2021, 10:49:15)  [GCC 9.4.0]
PEP 405 virtualenv detected: /home/hoon2/django/venv
Set PythonHome to /home/hoon2/django/venv
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x55e217b9ed40
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 801944 bytes (783 KB) for 10 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 2 seconds on interpreter 0x55e217b9ed40 pid: 27045 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 27045)
spawned uWSGI worker 1 (pid: 27048, cores: 1)
spawned uWSGI worker 2 (pid: 27049, cores: 1)
spawned uWSGI worker 3 (pid: 27050, cores: 1)
spawned uWSGI worker 4 (pid: 27051, cores: 1)
spawned uWSGI worker 5 (pid: 27052, cores: 1)
spawned uWSGI worker 6 (pid: 27053, cores: 1)
spawned uWSGI worker 7 (pid: 27054, cores: 1)
spawned uWSGI worker 8 (pid: 27055, cores: 1)
spawned uWSGI worker 9 (pid: 27056, cores: 1)
spawned uWSGI worker 10 (pid: 27057, cores: 1)
Internal Server Error: /
Traceback (most recent call last):
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/base.py", line 470, in parse
    compile_func = self.tags[command]
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/hoon2/django/./blog/views.py", line 5, in Mainpageview
    return render(request, 'blog/main.html', {})
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/loaders/base.py", line 29, in get_template
    return Template(
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/base.py", line 193, in compile_nodelist
    return parser.parse()
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/loader_tags.py", line 278, in do_extends
    nodelist = parser.parse()
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/loader_tags.py", line 216, in do_block
    nodelist = parser.parse(('endblock',))
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/base.py", line 472, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/base.py", line 522, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 11: 'static', expected 'endblock'. Did you forget to register or load this tag?
[pid: 27055|app: 0|req: 1/1] 192.168.10.101 () {70 vars in 1259 bytes} [Tue Aug 24 09:13:15 2021] GET / => generated 145332 bytes in 560 msecs (HTTP/1.1 500) 6 headers in 187 bytes (1 switches on core 0)
announcing my loyalty to the Emperor...
[pid: 27053|app: 0|req: 1/2] 192.168.10.101 () {70 vars in 1257 bytes} [Tue Aug 24 09:19:01 2021] GET / => generated 31190 bytes in 132 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
announcing my loyalty to the Emperor...
[pid: 27052|app: 0|req: 1/3] 192.168.10.101 () {70 vars in 1257 bytes} [Tue Aug 24 09:19:35 2021] GET / => generated 30232 bytes in 132 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
announcing my loyalty to the Emperor...
[pid: 27050|app: 0|req: 1/4] 192.168.10.101 () {70 vars in 1257 bytes} [Tue Aug 24 09:19:54 2021] GET / => generated 31190 bytes in 140 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
announcing my loyalty to the Emperor...
[pid: 27052|app: 0|req: 2/5] 192.168.10.101 () {70 vars in 1258 bytes} [Tue Aug 24 09:30:41 2021] GET / => generated 29267 bytes in 17 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
[pid: 27056|app: 0|req: 1/6] 192.168.10.101 () {70 vars in 1258 bytes} [Tue Aug 24 09:30:45 2021] GET / => generated 30225 bytes in 133 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
announcing my loyalty to the Emperor...
[pid: 27055|app: 0|req: 2/7] 192.168.10.101 () {70 vars in 1258 bytes} [Tue Aug 24 09:31:01 2021] GET / => generated 30225 bytes in 26 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
[pid: 27050|app: 0|req: 2/8] 192.168.10.101 () {70 vars in 1260 bytes} [Tue Aug 24 09:32:00 2021] GET / => generated 30225 bytes in 26 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
SIGINT/SIGQUIT received...killing workers...
Tue Aug 24 09:32:46 2021 - received message 0 from emperor
worker 2 buried after 2 seconds
worker 4 buried after 2 seconds
worker 5 buried after 2 seconds
worker 6 buried after 2 seconds
worker 8 buried after 2 seconds
worker 1 buried after 3 seconds
worker 3 buried after 3 seconds
worker 7 buried after 3 seconds
worker 9 buried after 3 seconds
worker 10 buried after 3 seconds
goodbye to uWSGI.
VACUUM: unix socket /home/hoon2/django/HPP.sock removed.
*** Starting uWSGI 2.0.19.1 (64bit) on [Tue Aug 24 09:32:51 2021] ***
compiled with version: 9.3.0 on 14 August 2021 08:43:18
os: Linux-5.11.0-27-generic #29~20.04.1-Ubuntu SMP Wed Aug 11 15:58:17 UTC 2021
nodename: hoon2-X205TA
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /etc/uwsgi/vassals
detected binary path: /usr/local/bin/uwsgi
chdir() to /home/hoon2/django/
your processes number limit is 7423
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /home/hoon2/django/HPP.sock fd 3
Python version: 3.8.10 (default, Jun  2 2021, 10:49:15)  [GCC 9.4.0]
PEP 405 virtualenv detected: /home/hoon2/django/venv
Set PythonHome to /home/hoon2/django/venv
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x5564a7954d40
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 801944 bytes (783 KB) for 10 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x5564a7954d40 pid: 27400 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 27400)
spawned uWSGI worker 1 (pid: 27403, cores: 1)
spawned uWSGI worker 2 (pid: 27404, cores: 1)
spawned uWSGI worker 3 (pid: 27405, cores: 1)
spawned uWSGI worker 4 (pid: 27406, cores: 1)
spawned uWSGI worker 5 (pid: 27407, cores: 1)
spawned uWSGI worker 6 (pid: 27408, cores: 1)
spawned uWSGI worker 7 (pid: 27409, cores: 1)
spawned uWSGI worker 8 (pid: 27410, cores: 1)
spawned uWSGI worker 9 (pid: 27411, cores: 1)
spawned uWSGI worker 10 (pid: 27412, cores: 1)
[pid: 27411|app: 0|req: 1/1] 192.168.10.101 () {70 vars in 1260 bytes} [Tue Aug 24 09:32:57 2021] GET / => generated 30225 bytes in 132 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
announcing my loyalty to the Emperor...
[pid: 27410|app: 0|req: 1/2] 192.168.10.101 () {70 vars in 1260 bytes} [Tue Aug 24 09:33:00 2021] GET / => generated 30225 bytes in 133 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
announcing my loyalty to the Emperor...
[pid: 27403|app: 0|req: 1/3] 192.168.10.101 () {70 vars in 1259 bytes} [Tue Aug 24 09:41:26 2021] GET / => generated 29267 bytes in 133 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
announcing my loyalty to the Emperor...
Tue Aug 24 09:42:01 2021 - received message 0 from emperor
SIGINT/SIGQUIT received...killing workers...
worker 1 buried after 2 seconds
worker 4 buried after 2 seconds
worker 6 buried after 2 seconds
worker 8 buried after 2 seconds
worker 9 buried after 2 seconds
worker 10 buried after 2 seconds
worker 2 buried after 3 seconds
worker 3 buried after 3 seconds
worker 5 buried after 3 seconds
worker 7 buried after 3 seconds
goodbye to uWSGI.
VACUUM: unix socket /home/hoon2/django/HPP.sock removed.
*** Starting uWSGI 2.0.19.1 (64bit) on [Tue Aug 24 09:42:05 2021] ***
compiled with version: 9.3.0 on 14 August 2021 08:43:18
os: Linux-5.11.0-27-generic #29~20.04.1-Ubuntu SMP Wed Aug 11 15:58:17 UTC 2021
nodename: hoon2-X205TA
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /etc/uwsgi/vassals
detected binary path: /usr/local/bin/uwsgi
chdir() to /home/hoon2/django/
your processes number limit is 7423
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /home/hoon2/django/HPP.sock fd 3
Python version: 3.8.10 (default, Jun  2 2021, 10:49:15)  [GCC 9.4.0]
PEP 405 virtualenv detected: /home/hoon2/django/venv
Set PythonHome to /home/hoon2/django/venv
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x561b0468fd40
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 801944 bytes (783 KB) for 10 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x561b0468fd40 pid: 27492 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 27492)
spawned uWSGI worker 1 (pid: 27494, cores: 1)
spawned uWSGI worker 2 (pid: 27495, cores: 1)
spawned uWSGI worker 3 (pid: 27496, cores: 1)
spawned uWSGI worker 4 (pid: 27497, cores: 1)
spawned uWSGI worker 5 (pid: 27498, cores: 1)
spawned uWSGI worker 6 (pid: 27499, cores: 1)
spawned uWSGI worker 7 (pid: 27500, cores: 1)
spawned uWSGI worker 8 (pid: 27501, cores: 1)
spawned uWSGI worker 9 (pid: 27502, cores: 1)
spawned uWSGI worker 10 (pid: 27503, cores: 1)
[pid: 27502|app: 0|req: 1/1] 192.168.10.101 () {70 vars in 1260 bytes} [Tue Aug 24 09:42:07 2021] GET / => generated 29267 bytes in 130 msecs (HTTP/1.1 200) 5 headers in 168 bytes (2 switches on core 0)
announcing my loyalty to the Emperor...
[pid: 27502|app: 0|req: 2/2] 192.168.10.101 () {70 vars in 1267 bytes} [Tue Aug 24 09:43:26 2021] GET / => generated 29267 bytes in 16 msecs (HTTP/1.1 200) 5 headers in 168 bytes (2 switches on core 0)
[pid: 27500|app: 0|req: 1/3] 192.168.10.101 () {68 vars in 1229 bytes} [Tue Aug 24 09:43:30 2021] GET / => generated 29267 bytes in 130 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
announcing my loyalty to the Emperor...
Internal Server Error: /
Traceback (most recent call last):
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/hoon2/django/./blog/views.py", line 5, in Mainpageview
    return render(request, 'blog/layout.html', {})
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/loader_tags.py", line 53, in render
    result = self.nodelist.render(context)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/base.py", line 988, in render
    output = self.filter_expression.resolve(context)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/base.py", line 671, in resolve
    obj = self.var.resolve(context)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/base.py", line 796, in resolve
    value = self._resolve_lookup(context)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/base.py", line 858, in _resolve_lookup
    current = current()
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/loader_tags.py", line 69, in super
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'BlockNode' object has no attribute 'context'. Did you use {{ block.super }} in a base template?
[pid: 27499|app: 0|req: 1/4] 192.168.10.101 () {70 vars in 1260 bytes} [Tue Aug 24 09:45:27 2021] GET / => generated 130023 bytes in 547 msecs (HTTP/1.1 500) 6 headers in 187 bytes (1 switches on core 0)
announcing my loyalty to the Emperor...
[pid: 27500|app: 0|req: 2/5] 192.168.10.101 () {70 vars in 1257 bytes} [Tue Aug 24 09:46:09 2021] GET / => generated 29267 bytes in 19 msecs (HTTP/1.1 200) 5 headers in 168 bytes (2 switches on core 0)
[pid: 27498|app: 0|req: 1/6] 192.168.10.101 () {70 vars in 1257 bytes} [Tue Aug 24 09:46:19 2021] GET / => generated 29267 bytes in 130 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
announcing my loyalty to the Emperor...
[pid: 27497|app: 0|req: 1/7] 192.168.10.101 () {70 vars in 1257 bytes} [Tue Aug 24 09:46:21 2021] GET / => generated 29267 bytes in 129 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
announcing my loyalty to the Emperor...
[pid: 27502|app: 0|req: 3/8] 192.168.10.101 () {70 vars in 1257 bytes} [Tue Aug 24 09:46:23 2021] GET / => generated 29267 bytes in 17 msecs (HTTP/1.1 200) 5 headers in 168 bytes (2 switches on core 0)
[pid: 27502|app: 0|req: 4/9] 192.168.10.101 () {70 vars in 1257 bytes} [Tue Aug 24 09:47:18 2021] GET / => generated 29267 bytes in 20 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
[pid: 27495|app: 0|req: 1/10] 192.168.10.101 () {70 vars in 1257 bytes} [Tue Aug 24 09:47:20 2021] GET / => generated 29267 bytes in 127 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
announcing my loyalty to the Emperor...
[pid: 27500|app: 0|req: 3/11] 192.168.10.101 () {70 vars in 1257 bytes} [Tue Aug 24 09:47:29 2021] GET / => generated 29267 bytes in 18 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
[pid: 27499|app: 0|req: 2/12] 192.168.10.101 () {70 vars in 1265 bytes} [Tue Aug 24 09:48:37 2021] GET / => generated 29267 bytes in 21 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
[pid: 27500|app: 0|req: 4/13] 192.168.10.101 () {70 vars in 1265 bytes} [Tue Aug 24 09:48:46 2021] GET / => generated 29267 bytes in 17 msecs (HTTP/1.1 200) 5 headers in 168 bytes (2 switches on core 0)
[pid: 27499|app: 0|req: 3/14] 192.168.10.101 () {70 vars in 1265 bytes} [Tue Aug 24 09:48:52 2021] GET / => generated 29267 bytes in 18 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
[pid: 27495|app: 0|req: 2/15] 192.168.10.101 () {70 vars in 1267 bytes} [Tue Aug 24 09:51:23 2021] GET / => generated 29267 bytes in 17 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
[pid: 27502|app: 0|req: 5/16] 192.168.10.101 () {70 vars in 1267 bytes} [Tue Aug 24 09:51:27 2021] GET / => generated 29267 bytes in 16 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
[pid: 27503|app: 0|req: 1/17] 192.168.10.101 () {70 vars in 1267 bytes} [Tue Aug 24 09:51:34 2021] GET / => generated 29267 bytes in 128 msecs (HTTP/1.1 200) 5 headers in 168 bytes (2 switches on core 0)
announcing my loyalty to the Emperor...
[pid: 27502|app: 0|req: 6/18] 192.168.10.101 () {70 vars in 1265 bytes} [Tue Aug 24 09:53:39 2021] GET / => generated 29267 bytes in 23 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
[pid: 27499|app: 0|req: 4/19] 192.168.10.101 () {68 vars in 1227 bytes} [Tue Aug 24 09:53:42 2021] GET / => generated 29267 bytes in 19 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
[pid: 27497|app: 0|req: 2/20] 192.168.10.101 () {70 vars in 1258 bytes} [Tue Aug 24 09:54:00 2021] GET / => generated 29267 bytes in 19 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
[pid: 27500|app: 0|req: 5/21] 192.168.10.101 () {70 vars in 1258 bytes} [Tue Aug 24 09:54:01 2021] GET / => generated 29267 bytes in 17 msecs (HTTP/1.1 200) 5 headers in 168 bytes (2 switches on core 0)
[pid: 27495|app: 0|req: 3/22] 192.168.10.101 () {70 vars in 1258 bytes} [Tue Aug 24 09:54:03 2021] GET / => generated 29267 bytes in 19 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
[pid: 27496|app: 0|req: 1/23] 192.168.10.101 () {70 vars in 1258 bytes} [Tue Aug 24 09:54:13 2021] GET / => generated 30225 bytes in 137 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
announcing my loyalty to the Emperor...
Not Found: /a2billing/customer/templates/default/footer.tpl
[pid: 27503|app: 0|req: 2/24] 192.168.10.101 () {40 vars in 628 bytes} [Tue Aug 24 10:00:51 2021] GET /a2billing/customer/templates/default/footer.tpl => generated 2595 bytes in 41 msecs (HTTP/1.1 404) 5 headers in 159 bytes (2 switches on core 0)
Internal Server Error: /
Traceback (most recent call last):
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/base.py", line 470, in parse
    compile_func = self.tags[command]
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/hoon2/django/./blog/views.py", line 5, in Mainpageview
    return render(request, 'blog/main.html', {})
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/loaders/base.py", line 29, in get_template
    return Template(
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/base.py", line 193, in compile_nodelist
    return parser.parse()
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/base.py", line 472, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/base.py", line 531, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 8: 'static'. Did you forget to register or load this tag?
[pid: 27496|app: 0|req: 2/25] 192.168.10.101 () {70 vars in 1258 bytes} [Tue Aug 24 10:01:25 2021] GET / => generated 115788 bytes in 404 msecs (HTTP/1.1 500) 6 headers in 187 bytes (1 switches on core 0)
Internal Server Error: /
Traceback (most recent call last):
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/base.py", line 470, in parse
    compile_func = self.tags[command]
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/hoon2/django/./blog/views.py", line 5, in Mainpageview
    return render(request, 'blog/main.html', {})
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/loaders/base.py", line 29, in get_template
    return Template(
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/base.py", line 193, in compile_nodelist
    return parser.parse()
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/base.py", line 472, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/base.py", line 531, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 8: 'static'. Did you forget to register or load this tag?
[pid: 27496|app: 0|req: 3/26] 192.168.10.101 () {70 vars in 1258 bytes} [Tue Aug 24 10:01:27 2021] GET / => generated 115788 bytes in 232 msecs (HTTP/1.1 500) 6 headers in 187 bytes (1 switches on core 0)
[pid: 27497|app: 0|req: 3/27] 192.168.10.101 () {70 vars in 1258 bytes} [Tue Aug 24 10:01:49 2021] GET / => generated 31188 bytes in 23 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
[pid: 27500|app: 0|req: 6/28] 192.168.10.101 () {34 vars in 392 bytes} [Tue Aug 24 10:18:18 2021] GET / => generated 31188 bytes in 22 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
[pid: 27501|app: 0|req: 1/29] 103.203.57.20 () {34 vars in 392 bytes} [Tue Aug 24 11:05:45 2021] GET / => generated 956 bytes in 123 msecs (HTTP/1.1 200) 5 headers in 166 bytes (1 switches on core 0)
announcing my loyalty to the Emperor...
Not Found: /robots.txt
[pid: 27500|app: 0|req: 7/30] 104.149.165.66 () {26 vars in 303 bytes} [Tue Aug 24 11:20:45 2021] HEAD /robots.txt => generated 2489 bytes in 39 msecs (HTTP/1.0 404) 5 headers in 159 bytes (1 switches on core 0)
[pid: 27501|app: 0|req: 2/31] 192.168.10.101 () {40 vars in 480 bytes} [Tue Aug 24 12:30:52 2021] GET / => generated 956 bytes in 12 msecs (HTTP/1.1 200) 5 headers in 166 bytes (1 switches on core 0)
Internal Server Error: /
Traceback (most recent call last):
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/hoon2/django/./blog/views.py", line 5, in Mainpageview
    return render(request, 'blog/layout.html', {})
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: blog/main.html
[pid: 27501|app: 0|req: 3/32] 192.168.10.101 () {70 vars in 1257 bytes} [Tue Aug 24 13:06:32 2021] GET / => generated 69783 bytes in 343 msecs (HTTP/1.1 500) 6 headers in 186 bytes (2 switches on core 0)
Internal Server Error: /
Traceback (most recent call last):
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/hoon2/django/./blog/views.py", line 5, in Mainpageview
    return render(request, 'blog/layout.html', {})
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: blog/main.html
[pid: 27496|app: 0|req: 4/33] 192.168.10.101 () {70 vars in 1257 bytes} [Tue Aug 24 13:06:36 2021] GET / => generated 69783 bytes in 172 msecs (HTTP/1.1 500) 6 headers in 186 bytes (1 switches on core 0)
SIGINT/SIGQUIT received...killing workers...
Tue Aug 24 13:17:12 2021 - received message 0 from emperor
worker 3 buried after 2 seconds
worker 5 buried after 2 seconds
worker 10 buried after 2 seconds
worker 1 buried after 3 seconds
worker 2 buried after 3 seconds
worker 4 buried after 3 seconds
worker 6 buried after 3 seconds
worker 7 buried after 3 seconds
worker 8 buried after 3 seconds
worker 9 buried after 3 seconds
goodbye to uWSGI.
VACUUM: unix socket /home/hoon2/django/HPP.sock removed.
*** Starting uWSGI 2.0.19.1 (64bit) on [Tue Aug 24 13:17:17 2021] ***
compiled with version: 9.3.0 on 14 August 2021 08:43:18
os: Linux-5.11.0-27-generic #29~20.04.1-Ubuntu SMP Wed Aug 11 15:58:17 UTC 2021
nodename: hoon2-X205TA
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /etc/uwsgi/vassals
detected binary path: /usr/local/bin/uwsgi
chdir() to /home/hoon2/django/
your processes number limit is 7423
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /home/hoon2/django/HPP.sock fd 3
Python version: 3.8.10 (default, Jun  2 2021, 10:49:15)  [GCC 9.4.0]
PEP 405 virtualenv detected: /home/hoon2/django/venv
Set PythonHome to /home/hoon2/django/venv
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x5631c069cd40
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 801944 bytes (783 KB) for 10 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x5631c069cd40 pid: 28771 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 28771)
spawned uWSGI worker 1 (pid: 28780, cores: 1)
spawned uWSGI worker 2 (pid: 28781, cores: 1)
spawned uWSGI worker 3 (pid: 28782, cores: 1)
spawned uWSGI worker 4 (pid: 28783, cores: 1)
spawned uWSGI worker 5 (pid: 28784, cores: 1)
spawned uWSGI worker 6 (pid: 28785, cores: 1)
spawned uWSGI worker 7 (pid: 28786, cores: 1)
spawned uWSGI worker 8 (pid: 28787, cores: 1)
spawned uWSGI worker 9 (pid: 28788, cores: 1)
spawned uWSGI worker 10 (pid: 28789, cores: 1)
Internal Server Error: /
Traceback (most recent call last):
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/hoon2/django/./blog/views.py", line 5, in Mainpageview
    return render(request, 'blog/layout.html', {})
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/loaders/base.py", line 29, in get_template
    return Template(
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/base.py", line 193, in compile_nodelist
    return parser.parse()
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/loader_tags.py", line 322, in do_include
    raise TemplateSyntaxError('Unknown argument for %r tag: %r.' %
django.template.exceptions.TemplateSyntaxError: Unknown argument for 'include' tag: "'".
[pid: 28788|app: 0|req: 1/1] 192.168.10.101 () {70 vars in 1260 bytes} [Tue Aug 24 13:17:21 2021] GET / => generated 126270 bytes in 608 msecs (HTTP/1.1 500) 6 headers in 187 bytes (1 switches on core 0)
announcing my loyalty to the Emperor...
Internal Server Error: /
Traceback (most recent call last):
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/base.py", line 470, in parse
    compile_func = self.tags[command]
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/hoon2/django/./blog/views.py", line 5, in Mainpageview
    return render(request, 'blog/layout.html', {})
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/loader_tags.py", line 183, in render
    template = context.template.engine.select_template(template_name)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/engine.py", line 174, in select_template
    return self.get_template(template_name)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/loaders/base.py", line 29, in get_template
    return Template(
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/base.py", line 193, in compile_nodelist
    return parser.parse()
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/base.py", line 472, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/base.py", line 531, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 8: 'static'. Did you forget to register or load this tag?
[pid: 28789|app: 0|req: 1/2] 192.168.10.101 () {70 vars in 1258 bytes} [Tue Aug 24 13:17:53 2021] GET / => generated 138296 bytes in 587 msecs (HTTP/1.1 500) 6 headers in 187 bytes (1 switches on core 0)
announcing my loyalty to the Emperor...
Not Found: /zdrtyhmcfghn
[pid: 28785|app: 0|req: 1/3] 192.168.10.101 () {40 vars in 596 bytes} [Tue Aug 24 13:19:09 2021] GET /zdrtyhmcfghn => generated 2490 bytes in 142 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
announcing my loyalty to the Emperor...
Internal Server Error: /
Traceback (most recent call last):
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/loader_tags.py", line 183, in render
    template = context.template.engine.select_template(template_name)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/engine.py", line 180, in select_template
    raise TemplateDoesNotExist(', '.join(not_found))
django.template.exceptions.TemplateDoesNotExist: portfolio_grid.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/hoon2/django/./blog/views.py", line 5, in Mainpageview
    return render(request, 'blog/layout.html', {})
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/backends/django.py", line 63, in render
    reraise(exc, self.backend)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/backends/django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: portfolio_grid.html
[pid: 28788|app: 0|req: 2/4] 192.168.10.101 () {70 vars in 1259 bytes} [Tue Aug 24 13:19:37 2021] GET / => generated 110567 bytes in 266 msecs (HTTP/1.1 500) 6 headers in 187 bytes (1 switches on core 0)
Internal Server Error: /
Traceback (most recent call last):
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/loader_tags.py", line 183, in render
    template = context.template.engine.select_template(template_name)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/engine.py", line 180, in select_template
    raise TemplateDoesNotExist(', '.join(not_found))
django.template.exceptions.TemplateDoesNotExist: portfolio_grid.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/hoon2/django/./blog/views.py", line 5, in Mainpageview
    return render(request, 'blog/layout.html', {})
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/backends/django.py", line 63, in render
    reraise(exc, self.backend)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/backends/django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: portfolio_grid.html
[pid: 28782|app: 0|req: 1/5] 192.168.10.101 () {70 vars in 1259 bytes} [Tue Aug 24 13:19:55 2021] GET / => generated 110567 bytes in 519 msecs (HTTP/1.1 500) 6 headers in 187 bytes (1 switches on core 0)
announcing my loyalty to the Emperor...
Internal Server Error: /
Traceback (most recent call last):
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/loader_tags.py", line 183, in render
    template = context.template.engine.select_template(template_name)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/engine.py", line 180, in select_template
    raise TemplateDoesNotExist(', '.join(not_found))
django.template.exceptions.TemplateDoesNotExist: portfolio_grid.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/hoon2/django/./blog/views.py", line 5, in Mainpageview
    return render(request, 'blog/layout.html', {})
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/backends/django.py", line 63, in render
    reraise(exc, self.backend)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/backends/django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: portfolio_grid.html
[pid: 28788|app: 0|req: 3/6] 192.168.10.101 () {70 vars in 1260 bytes} [Tue Aug 24 13:21:19 2021] GET / => generated 110568 bytes in 236 msecs (HTTP/1.1 500) 6 headers in 187 bytes (2 switches on core 0)
Internal Server Error: /
Traceback (most recent call last):
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/loader_tags.py", line 183, in render
    template = context.template.engine.select_template(template_name)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/engine.py", line 180, in select_template
    raise TemplateDoesNotExist(', '.join(not_found))
django.template.exceptions.TemplateDoesNotExist: portfolio_grid.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/hoon2/django/./blog/views.py", line 5, in Mainpageview
    return render(request, 'blog/layout.html', {})
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/backends/django.py", line 63, in render
    reraise(exc, self.backend)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/backends/django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: portfolio_grid.html
[pid: 28783|app: 0|req: 1/7] 192.168.10.101 () {70 vars in 1260 bytes} [Tue Aug 24 13:21:39 2021] GET / => generated 110629 bytes in 519 msecs (HTTP/1.1 500) 6 headers in 187 bytes (1 switches on core 0)
announcing my loyalty to the Emperor...
Internal Server Error: /
Traceback (most recent call last):
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/loader_tags.py", line 183, in render
    template = context.template.engine.select_template(template_name)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/engine.py", line 180, in select_template
    raise TemplateDoesNotExist(', '.join(not_found))
django.template.exceptions.TemplateDoesNotExist: about.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/hoon2/django/./blog/views.py", line 5, in Mainpageview
    return render(request, 'blog/layout.html', {})
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/backends/django.py", line 63, in render
    reraise(exc, self.backend)
  File "/home/hoon2/django/venv/lib/python3.8/site-packages/django/template/backends/django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: about.html
[pid: 28780|app: 0|req: 1/8] 192.168.10.101 () {70 vars in 1260 bytes} [Tue Aug 24 13:22:03 2021] GET / => generated 111568 bytes in 527 msecs (HTTP/1.1 500) 6 headers in 187 bytes (1 switches on core 0)
announcing my loyalty to the Emperor...
[pid: 28784|app: 0|req: 1/9] 192.168.10.101 () {70 vars in 1260 bytes} [Tue Aug 24 13:22:12 2021] GET / => generated 31263 bytes in 144 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
announcing my loyalty to the Emperor...
Not Found: /api/jsonws/invoke
[pid: 28788|app: 0|req: 4/10] 192.168.10.101 () {42 vars in 672 bytes} [Tue Aug 24 14:24:01 2021] POST /api/jsonws/invoke => generated 2510 bytes in 32 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
Not Found: /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
[pid: 28784|app: 0|req: 2/11] 192.168.10.101 () {42 vars in 774 bytes} [Tue Aug 24 14:24:01 2021] POST /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php => generated 2609 bytes in 40 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
Not Found: /index.php
[pid: 28784|app: 0|req: 3/12] 192.168.10.101 () {38 vars in 782 bytes} [Tue Aug 24 14:24:06 2021] GET /index.php?s=/Index/\think\app/invokefunction&function=call_user_func_array&vars[0]=md5&vars[1][]=HelloThinkPHP21 => generated 2604 bytes in 31 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
[pid: 28789|app: 0|req: 2/13] 192.168.10.101 () {38 vars in 618 bytes} [Tue Aug 24 14:24:06 2021] GET /?XDEBUG_SESSION_START=phpstorm => generated 31263 bytes in 37 msecs (HTTP/1.1 200) 5 headers in 168 bytes (2 switches on core 0)
Not Found: /mifs/.;/services/LogService
[pid: 28786|app: 0|req: 1/14] 192.168.10.101 () {44 vars in 741 bytes} [Tue Aug 24 14:24:09 2021] POST /mifs/.;/services/LogService => generated 2542 bytes in 113 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
announcing my loyalty to the Emperor...
Not Found: /Autodiscover/Autodiscover.xml
[pid: 28787|app: 0|req: 1/15] 192.168.10.101 () {42 vars in 698 bytes} [Tue Aug 24 14:24:12 2021] POST /Autodiscover/Autodiscover.xml => generated 2546 bytes in 114 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
announcing my loyalty to the Emperor...
Not Found: /wp-content/plugins/wp-file-manager/readme.txt
[pid: 28783|app: 0|req: 2/16] 192.168.10.101 () {38 vars in 649 bytes} [Tue Aug 24 14:24:15 2021] GET /wp-content/plugins/wp-file-manager/readme.txt => generated 2593 bytes in 31 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
Not Found: /console/
[pid: 28789|app: 0|req: 3/17] 192.168.10.101 () {38 vars in 575 bytes} [Tue Aug 24 14:24:17 2021] GET /console/ => generated 2482 bytes in 29 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
Not Found: /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
[pid: 28782|app: 0|req: 2/18] 192.168.10.101 () {40 vars in 686 bytes} [Tue Aug 24 14:24:17 2021] GET /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php => generated 2608 bytes in 31 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
Not Found: /_ignition/execute-solution
[pid: 28788|app: 0|req: 5/19] 192.168.10.101 () {40 vars in 664 bytes} [Tue Aug 24 14:24:19 2021] GET /_ignition/execute-solution => generated 2536 bytes in 31 msecs (HTTP/1.1 404) 5 headers in 159 bytes (2 switches on core 0)
[pid: 28786|app: 0|req: 2/20] 192.168.10.101 () {50 vars in 766 bytes} [Tue Aug 24 17:12:01 2021] GET / => generated 31263 bytes in 70 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
[pid: 28789|app: 0|req: 4/21] 192.168.10.101 () {50 vars in 765 bytes} [Tue Aug 24 18:09:54 2021] GET / => generated 31263 bytes in 31 msecs (HTTP/1.1 200) 5 headers in 168 bytes (2 switches on core 0)
[pid: 28789|app: 0|req: 5/22] 192.168.10.101 () {34 vars in 395 bytes} [Tue Aug 24 18:24:43 2021] OPTIONS / => generated 31263 bytes in 34 msecs (HTTP/1.1 200) 5 headers in 168 bytes (2 switches on core 0)
Not Found: /owa/auth/logon.aspx
[pid: 28788|app: 0|req: 6/23] 192.168.10.101 () {40 vars in 573 bytes} [Tue Aug 24 19:18:28 2021] GET /owa/auth/logon.aspx?url=https%3a%2f%2f1%2fecp%2f => generated 2540 bytes in 31 msecs (HTTP/1.1 404) 5 headers in 159 bytes (2 switches on core 0)
Invalid HTTP_HOST header: 'www.baidu.com'. You may need to add 'www.baidu.com' to ALLOWED_HOSTS.
Bad Request: /cache/global/img/gs.gif
[pid: 28789|app: 0|req: 6/24] 185.216.140.186 () {32 vars in 436 bytes} [Tue Aug 24 19:35:36 2021] GET /cache/global/img/gs.gif => generated 57550 bytes in 175 msecs (HTTP/1.1 400) 3 headers in 116 bytes (1 switches on core 0)
Invalid HTTP_HOST header: '192.168.0.1:443'. You may need to add '192.168.0.1' to ALLOWED_HOSTS.
Bad Request: /GponForm/diag_Form
[pid: 28789|app: 0|req: 7/25] 192.168.10.101 () {44 vars in 601 bytes} [Tue Aug 24 20:54:37 2021] POST /GponForm/diag_Form?style/ => generated 58649 bytes in 151 msecs (HTTP/1.1 400) 3 headers in 116 bytes (1 switches on core 0)
[pid: 28789|app: 0|req: 8/26] 192.168.10.101 () {40 vars in 563 bytes} [Tue Aug 24 21:07:34 2021] GET / => generated 31262 bytes in 32 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
[pid: 28789|app: 0|req: 9/27] 188.166.58.250 () {34 vars in 481 bytes} [Tue Aug 24 21:07:44 2021] GET / => generated 31262 bytes in 33 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
[pid: 28789|app: 0|req: 10/28] 64.62.197.62 () {28 vars in 304 bytes} [Tue Aug 24 21:52:41 2021] GET / => generated 31262 bytes in 36 msecs (HTTP/1.1 200) 5 headers in 168 bytes (1 switches on core 0)
